using System.Collections;
using System.Diagnostics;
using System.Reflection;
using Mono.Cecil;
using Mono.Cecil.Cil;
using Mono.Cecil.Rocks;

namespace RenderiteGenerator;

public class Generator : IDisposable
{
    private readonly Stream _fileStream;
    private readonly StreamWriter _writer;
    private readonly Assembly _assembly;
    private readonly AssemblyDefinition _cecilAssembly;
    private readonly bool _verbose;
    private readonly bool _ilVerbose;
    private readonly string _engineVersion;

    private readonly List<Type> _generatedTypes = [];
    private readonly Queue<Type> _typesToGenerate = [];

    private readonly Type[] _types;
    private readonly Type _iMemoryPackable;
    
    public Generator(GeneratorOptions options)
    {
        options.OutputZigFile ??= DetermineDefaultOutputPath();
        
        if(File.Exists(options.OutputZigFile))
            File.Delete(options.OutputZigFile);
        
        this._assembly = Assembly.LoadFrom(options.AssemblyPath);
        this._cecilAssembly = AssemblyDefinition.ReadAssembly(options.AssemblyPath);
        this._fileStream = File.OpenWrite(options.OutputZigFile);
        this._writer = new StreamWriter(this._fileStream);
        this._verbose = options.Verbose;
        this._ilVerbose = options.IlVerbose;

        this._engineVersion = "Unknown";
        try
        {
            Assembly frooxEngine =
                Assembly.LoadFrom(Path.Combine(Path.GetDirectoryName(options.AssemblyPath)!, "FrooxEngine.dll"));

            this._engineVersion = frooxEngine.FullName!;
        }
        catch(Exception e)
        {
            Console.WriteLine($"Couldn't get FrooxEngine assembly to determine version: {e}");
        }

        this._types = this._assembly.GetTypes();
        this._iMemoryPackable = this._types.First(t => t.Name == "IMemoryPackable");
        
        Console.WriteLine($"Generating for {this._engineVersion}");
    }

    private static string DetermineDefaultOutputPath()
    {
        Process process = Process.Start(new ProcessStartInfo()
        {
            FileName = "git",
            Arguments = "rev-parse --show-toplevel",
            UseShellExecute = false,
            RedirectStandardOutput = true,
        })!;
        process.WaitForExit();
        if (process.ExitCode != 0)
            throw new Exception("Git exited with exit code " + process.ExitCode);

        string? output = process.StandardOutput.ReadLine();
        if (output == null)
            throw new Exception("Git returned no output");
        
        return Path.Combine(output, "renderite", "shared.zig");
    }

    public void Run()
    {
        this._writer.WriteLine("//! This file is automatically generated by RenderiteGenerator. Please do not modify this file.");
        this._writer.WriteLine($"// Generated for {this._engineVersion}\n");
        
        this._writer.WriteLine("const buffer = @import(\"buffer.zig\");");
        this._writer.WriteLine("const SharedMemoryBufferDescriptor = buffer.SharedMemoryBufferDescriptor;");
        this._writer.WriteLine();
        this._writer.WriteLine("const serialization = @import(\"serialization.zig\");");
        this._writer.WriteLine("const IpcDeserializer = serialization.IpcDeserializer;");
        this._writer.WriteLine("const IpcSerializer = serialization.IpcSerializer;");
        this._writer.WriteLine();
        
        Console.WriteLine("Generating polymorphic entity enums...");
        this._writer.WriteLine("// Polymorphic entity enums (PolymorphicMemoryPackableEntity<T>)");
        Type polymorphicType = this._types.First(t => t.Name == "PolymorphicMemoryPackableEntity`1").GetGenericTypeDefinition();
        foreach (Type type in this._types.Where(t =>
                 {
                     if (t.BaseType is not { IsGenericType: true })
                         return false;
                     
                     return t.BaseType.GetGenericTypeDefinition() == polymorphicType;
                 }))
        {
            this.WritePolymorphicEnum(type);
        }

        Console.WriteLine("Generating enums...");
        this._writer.WriteLine("// Generated Enums");
        foreach (Type type in this._types.Where(t => t.IsEnum))
        {
            this._generatedTypes.Add(type);
            this.WriteEnum(type);
        }

        Console.WriteLine("Generating structs...");
        this._writer.WriteLine("// Generated Structs");
        foreach (Type type in this._types.Where(t => t != this._iMemoryPackable && !t.IsAbstract && t.IsAssignableTo(this._iMemoryPackable)))
        {
            this._generatedTypes.Add(type);
            this.WriteStruct(type, true);
        }
        
        Console.WriteLine("Generating remaining structs...");
        while (this._typesToGenerate.TryDequeue(out Type? type))
        {
            if(this._generatedTypes.Contains(type) || type.IsAbstract)
                continue;
            
            this._generatedTypes.Add(type);
            this.WriteStruct(type);
        }
    }

    private void WriteEnum(Type t)
    {
        if(this._verbose)
            Console.WriteLine($"\tWriting enum {t.FullName}");

        Array values = Enum.GetValues(t);

        FieldInfo valueField = t.GetField("value__")!;
        Type underlyingType = valueField.FieldType;

        string enumName = t.Name;

        if (t.DeclaringType != null)
        {
            enumName = t.DeclaringType.Name + '_' + enumName;
        }
        
        this._writer.WriteLine($"pub const {enumName} = enum({MapToZigType(underlyingType)}) {{");

        List<string> names = [];
        foreach (object enumVal in values)
        {
            string name = enumVal.ToString()!;
            
            if(names.Contains(name))
                continue;
            
            names.Add(name);
            
            // workaround for enums that aren't int. this effectively casts to the underlying enum type
            object num = valueField.GetValue(enumVal)!;
            
            this._writer.WriteLine($"\t{name} = {num},");
        }
        
        this._writer.WriteLine("};\n");
    }
    
    private void WriteStruct(Type type, bool isPackable = false)
    {
        if(this._verbose)
            Console.WriteLine($"\tWriting struct {type.FullName}");
        
        // if we were called from a place that didn't already check if we're a packable, check
        if (!isPackable)
            isPackable = type.IsAssignableTo(this._iMemoryPackable);
        
        string structName = type.Name;
        
        this._writer.WriteLine($"pub const {structName} = struct {{");
        FieldInfo[] fields = type.GetFields();
        foreach (FieldInfo field in fields)
        {
            this._writer.WriteLine($"\t{field.Name}: {MapToZigType(field.FieldType)},");
        }

        if (isPackable && fields.Length > 0)
        {
            this._writer.WriteLine();
            this._writer.WriteLine($"\tpub fn write(self: {structName}, ipc: IpcSerializer) !void {{");
            bool generated = WritePackFunction(type, type.GetMethod("Pack")!);
            if(!generated) WritePackDiscard();
            this._writer.WriteLine("\t}\n");
            
            this._writer.WriteLine($"\tpub fn read(ipc: IpcDeserializer) !{structName} {{");
            this._writer.WriteLine($"\t\tvar self: {structName} = undefined;");
            generated = WritePackFunction(type, type.GetMethod("Unpack")!);
            if(!generated) WritePackDiscard(false);
            this._writer.WriteLine("\t\treturn self;");
            this._writer.WriteLine("\t}");
        }
        
        this._writer.WriteLine("};\n");
    }

    private bool WritePackFunction(Type type, MethodInfo method)
    {
        bool written = false;
        
        if(_ilVerbose)
            this._writer.WriteLine($"\t\t// {method.Name} {type.Name}");

        TypeDefinition typeDef = this._cecilAssembly.MainModule.GetType(type.Namespace + '.' + type.Name);
        MethodDefinition? methodDef = typeDef.GetMethods().FirstOrDefault(m => m.Name == method.Name);
        if (methodDef == null)
        {
            if (type.BaseType == null)
            {
                // this should never happen
                this._writer.WriteLine($"\t\t// BUG: {type.Name} has no explicitly defined method named {method.Name}, and has no base type");
                return written;
            }
            
            if(this._ilVerbose)
                this._writer.WriteLine($"\t\t// NOTE: {type.Name} has no explicitly defined method named {method.Name}, trying {type.BaseType?.Name}.{method.Name}");

            written |= WritePackFunction(type.BaseType!, type.BaseType!.GetMethod(method.Name)!);
            return written;
        }

        Queue<string> names = new();
        foreach (Instruction instruction in methodDef.Body.Instructions)
        {
            // if (this._ilVerbose)
            // {
            //     this._writer.Write("\t\t// ");
            //     this._writer.WriteLine(instruction.ToString());
            // }

            if (instruction.OpCode.Code is Code.Ldfld or Code.Ldflda)
            {
                string name = ((FieldReference)instruction.Operand).Name;
                names.Enqueue(name);
                if (this._ilVerbose)
                    this._writer.WriteLine($"\t\t// {instruction.OpCode.Code} {name}");
            }

            if (instruction.OpCode.Code is Code.Call && instruction.Operand is MethodReference callRef)
            {
                switch (callRef.Name)
                {
                    // Write single value or packed boolean
                    case "Write" when callRef.Parameters.Count == 1:
                    {
                        string name = names.DequeueLast();
                        this._writer.WriteLine($"\t\ttry ipc.write(@TypeOf(self.{name}), self.{name});");
                        written = true;
                        break;
                    }
                    case "Write" when callRef.Parameters.All(p => p.ParameterType.Name == "Boolean"):
                    {
                        List<string> paramsList = names.Select(n => "self." + n).ToList();
                        while (paramsList.Count < 8)
                        {
                            paramsList.Add("false");
                        }
                        this._writer.WriteLine($"\t\ttry ipc.write{paramsList.Count}PackedBools({string.Join(", ", paramsList)});");
                        names.Clear();
                        written = true;
                        break;
                    }
                    // Read single value or packed boolean
                    case "Read" when callRef.Parameters.Count == 1:
                    {
                        string name = names.DequeueLast();
                        this._writer.WriteLine($"\t\tself.{name} = try ipc.read(@TypeOf(self.{name}));");
                        written = true;
                        break;
                    }
                    case "Read" when callRef.Parameters.All(p => p.ParameterType.Name == "Boolean&"):
                    {
                        List<string> paramsList = names.Select(n => "self." + n).ToList();
                        // TODO: ceil to nearest multiple of 8
                        // FE doesn't pack more than 1 byte at a time so its not particularly important
                        while (paramsList.Count < 8)
                        {
                            paramsList.Add("_");
                        }
                        this._writer.WriteLine($"\t\t{string.Join(", ", paramsList)} = try ipc.read{paramsList.Count}PackedBools();");
                        names.Clear();
                        written = true;
                        break;
                    }
                    // Write list
                    case "WriteValueList":
                    {
                        string name = names.DequeueLast();
                        this._writer.WriteLine($"\t\ttry ipc.writeList(@TypeOf(self.{name}), self.{name});");
                        written = true;
                        break;
                    }
                    // Read list
                    case "ReadValueList":
                    {
                        string name = names.DequeueLast();
                        this._writer.WriteLine($"\t\tself.{name} = try ipc.readList(@TypeOf(self.{name}));");
                        written = true;
                        break;
                    }
                    // Packing methods
                    case "Pack" or "Unpack":
                    {
                        MethodInfo? subMethod = type.BaseType?.GetMethod(method.Name);
                        if (subMethod == null)
                        {
                            this._writer.WriteLine($"\t\t// FIXME: Could not find {method.Name} on {type.BaseType}");
                            written = true;
                            continue;
                        }
                        written |= WritePackFunction(type.BaseType!, subMethod);
                        break;
                    }
                    default:
                        this._writer.WriteLine($"\t\t// FIXME: Unknown {callRef.GetType().Name} {callRef}");
                        break;
                }
            }
        }

        if(_ilVerbose)
            this._writer.WriteLine($"\t\t// {type.Name} {method.Name.ToLower()}ed");

        return written;
    }

    private void WritePackDiscard(bool self = true)
    {
        if (self)
            this._writer.WriteLine("\t\t_ = self;");
        else
            this._writer.WriteLine("\t\t_ = &self; // FIXME: Type not generating any members");

        this._writer.WriteLine("\t\t_ = ipc;");
    }
    
    private void WritePolymorphicEnum(Type type)
    {
        if(this._verbose)
            Console.WriteLine($"\tWriting polymorphic enum {type.FullName}");

        string enumName = type.Name;

        
        this._writer.WriteLine($"pub const {enumName}Types = enum(i32) {{");

        TypeDefinition typeDef = this._cecilAssembly.MainModule.GetType(type.FullName);
        MethodDefinition? ctor = typeDef.GetStaticConstructor();
        if (ctor == null)
            throw new Exception($"Couldn't find static constructor for {enumName}");

        List<string> typeNames = [];
        
        foreach (Instruction instruction in ctor.Body.Instructions)
        {
            if (instruction.OpCode.Code != Code.Ldtoken) continue;

            string name = ((TypeDefinition)instruction.Operand).Name;
            this._writer.WriteLine($"\t{name},");
            typeNames.Add(name);
        }
        
        this._writer.WriteLine($"}};\npub const {enumName} = union({enumName}Types) {{");
        foreach (string name in typeNames)
        {
            this._writer.WriteLine($"\t{name}: {name},");
        }
        this._writer.WriteLine("};\n");
    }

    private string MapToZigType(Type type)
    {
        if (type == typeof(string))
            return "[]const u16";
        
        if (type == typeof(byte))
            return "u8";
        if (type == typeof(sbyte))
            return "i8";
        
        if (type == typeof(short))
            return "i16";
        if (type == typeof(ushort))
            return "u16";
        
        if (type == typeof(int))
            return "i32";
        if (type == typeof(uint))
            return "u32";
        
        if (type == typeof(long))
            return "i64";
        if (type == typeof(ulong))
            return "u64";
        
        if (type == typeof(Int128))
            return "i128";
        if (type == typeof(UInt128))
            return "u128";

        if (type == typeof(float))
            return "f32";
        if (type == typeof(double))
            return "f64";

        if (type == typeof(bool))
            return "bool";

        switch (type.Name)
        {
            case "RenderVector2":
                return "@Vector(2, f32)";
            case "RenderVector2i":
                return "@Vector(2, i32)";
            case "RenderVector3":
                return "@Vector(3, f32)";
            case "RenderVector3i":
                return "@Vector(3, i32)";
            case "RenderVector4" or "RenderQuaternion":
                return "@Vector(4, f32)";
            case "RenderVector4i":
                return "@Vector(4, i32)";
        }

        if (typeof(IEnumerable).IsAssignableFrom(type))
            return $"[]const {MapToZigType(type.GenericTypeArguments.First())}";
        
        if(type.Name == "Nullable`1")
            return $"?{MapToZigType(type.GenericTypeArguments.First())}";

        if (type.Name.StartsWith("SharedMemoryBufferDescriptor"))
            return "SharedMemoryBufferDescriptor";

        if (type.IsGenericType)
            return $"{type.Name.Remove(type.Name.IndexOf('`'))}({string.Join(", ", type.GenericTypeArguments.Select(MapToZigType))})";

        if (!this._generatedTypes.Contains(type))
        {
            if (type.Assembly == this._assembly)
                this._typesToGenerate.Enqueue(type);
        }

        return type.Name;
    }

    public void Dispose()
    {
        this._writer.Flush();
        this._fileStream.Flush();
        
        this._writer.Dispose();
        this._fileStream.Dispose();
        GC.SuppressFinalize(this);
    }
}