using System.Collections;
using System.Diagnostics;
using System.Reflection;
using Mono.Cecil;
using Mono.Cecil.Cil;

namespace RenderiteGenerator;

public class Generator : IDisposable
{
    private readonly Stream _fileStream;
    private readonly StreamWriter _writer;
    private readonly Assembly _assembly;
    private readonly AssemblyDefinition _cecilAssembly;
    private readonly bool _verbose;
    private readonly bool _ilVerbose;
    private readonly string _engineVersion;

    private readonly List<Type> _generatedTypes = [];
    private readonly Queue<Type> _typesToGenerate = [];

    private readonly Type[] _types;
    private readonly Type _iMemoryPackable;
    
    public Generator(GeneratorOptions options)
    {
        options.OutputZigFile ??= DetermineDefaultOutputPath();
        
        if(File.Exists(options.OutputZigFile))
            File.Delete(options.OutputZigFile);
        
        this._assembly = Assembly.LoadFrom(options.AssemblyPath);
        this._cecilAssembly = AssemblyDefinition.ReadAssembly(options.AssemblyPath);
        this._fileStream = File.OpenWrite(options.OutputZigFile);
        this._writer = new StreamWriter(this._fileStream);
        this._verbose = options.Verbose;
        this._ilVerbose = options.IlVerbose;

        this._engineVersion = "Unknown";
        try
        {
            Assembly frooxEngine =
                Assembly.LoadFrom(Path.Combine(Path.GetDirectoryName(options.AssemblyPath)!, "FrooxEngine.dll"));

            this._engineVersion = frooxEngine.FullName!;
        }
        catch(Exception e)
        {
            Console.WriteLine($"Couldn't get FrooxEngine assembly to determine version: {e}");
        }

        this._types = this._assembly.GetTypes();
        this._iMemoryPackable = this._types.First(t => t.Name == "IMemoryPackable");
        
        Console.WriteLine($"Generating for {this._engineVersion}");
    }

    private static string DetermineDefaultOutputPath()
    {
        Process process = Process.Start(new ProcessStartInfo()
        {
            FileName = "git",
            Arguments = "rev-parse --show-toplevel",
            UseShellExecute = false,
            RedirectStandardOutput = true,
        })!;
        process.WaitForExit();
        if (process.ExitCode != 0)
            throw new Exception("Git exited with exit code " + process.ExitCode);

        string? output = process.StandardOutput.ReadLine();
        if (output == null)
            throw new Exception("Git returned no output");
        
        return Path.Combine(output, "renderite", "shared.zig");
    }

    public void Run()
    {
        this._writer.WriteLine("//! This file is automatically generated by RenderiteGenerator. Please do not modify this file.");
        this._writer.WriteLine($"// Generated for {this._engineVersion}\n");
        
        this._writer.WriteLine("const buffer = @import(\"buffer.zig\");");
        this._writer.WriteLine("const SharedMemoryBufferDescriptor = buffer.SharedMemoryBufferDescriptor;");
        this._writer.WriteLine();
        this._writer.WriteLine("const serialization = @import(\"serialization.zig\")");
        this._writer.WriteLine("const IpcDeserializer = serialization.IpcDeserializer;");
        this._writer.WriteLine("const IpcSerializer = serialization.IpcSerializer;");
        this._writer.WriteLine();

        Console.WriteLine("Generating enums...");
        this._writer.WriteLine("// Generated Enums");
        foreach (Type type in this._types.Where(t => t.IsEnum))
        {
            this._generatedTypes.Add(type);
            this.WriteEnum(type);
        }

        Console.WriteLine("Generating structs...");
        this._writer.WriteLine("// Generated Structs");
        foreach (Type type in this._types.Where(t => t != this._iMemoryPackable && !t.IsAbstract && t.IsAssignableTo(this._iMemoryPackable)))
        {
            this._generatedTypes.Add(type);
            this.WriteStruct(type, true);
        }
        
        Console.WriteLine("Generating remaining structs...");
        while (this._typesToGenerate.TryDequeue(out Type? type))
        {
            if(this._generatedTypes.Contains(type))
                continue;
            
            this._generatedTypes.Add(type);
            this.WriteStruct(type);
        }
    }

    private void WriteEnum(Type t)
    {
        if(this._verbose)
            Console.WriteLine($"\tWriting enum {t.FullName}");

        Array values = Enum.GetValues(t);

        FieldInfo valueField = t.GetField("value__")!;
        Type underlyingType = valueField.FieldType;

        string enumName = t.Name;

        if (t.DeclaringType != null)
        {
            enumName = t.DeclaringType.Name + '_' + enumName;
        }
        
        this._writer.WriteLine($"pub const {enumName} = enum({MapToZigType(underlyingType)}) {{");

        List<string> names = [];
        foreach (object enumVal in values)
        {
            string name = enumVal.ToString()!;
            
            if(names.Contains(name))
                continue;
            
            names.Add(name);
            
            // workaround for enums that aren't int. this effectively casts to the underlying enum type
            object num = valueField.GetValue(enumVal)!;
            
            this._writer.WriteLine($"\t{name} = {num},");
        }
        
        this._writer.WriteLine("};\n");
    }
    
    private void WriteStruct(Type type, bool isPackable = false)
    {
        if(this._verbose)
            Console.WriteLine($"\tWriting struct {type.FullName}");
        
        // if we were called from a place that didn't already check if we're a packable, check
        if (!isPackable)
            isPackable = type.IsAssignableTo(this._iMemoryPackable);
        
        string structName = type.Name;
        
        this._writer.WriteLine($"pub const {structName} = struct {{");
        foreach (FieldInfo field in type.GetFields())
        {
            this._writer.WriteLine($"\t{field.Name}: {MapToZigType(field.FieldType)},");
        }

        if (isPackable)
        {
            this._writer.WriteLine();
            this._writer.WriteLine($"\tpub fn write(self: {structName}, writer: IpcSerializer) !void {{");
            WritePackFunction(type, type.GetMethod("Pack")!);
            this._writer.WriteLine("\t}\n");
            
            this._writer.WriteLine($"\tpub fn read(self: {structName}, reader: IpcDeserializer) !void {{");
            WritePackFunction(type, type.GetMethod("Unpack")!);
            this._writer.WriteLine("\t}");
        }
        
        this._writer.WriteLine("};\n");
    }

    private void WritePackFunction(Type type, MethodInfo method)
    {
        if(_ilVerbose)
            this._writer.WriteLine($"\t\t// {method.Name} {type.Name}");

        TypeDefinition typeDef = this._cecilAssembly.MainModule.GetType(type.Namespace + '.' + type.Name);
        MethodDefinition? methodDef = typeDef.Methods.FirstOrDefault(m => m.Name == method.Name);
        if (methodDef == null)
            return;

        string name = null!;
        foreach (Instruction instruction in methodDef.Body.Instructions)
        {
            // if (this._ilVerbose)
            // {
            //     this._writer.Write("\t\t// ");
            //     this._writer.WriteLine(instruction.ToString());
            // }

            if (instruction.OpCode.Code is Code.Ldfld or Code.Ldflda)
            {
                name = ((FieldReference)instruction.Operand).Name;
                if (this._ilVerbose)
                    this._writer.WriteLine($"\t\t// {instruction.OpCode.Code} {name}");
            }

            if (instruction.OpCode.Code is Code.Call && instruction.Operand is MethodReference callRef)
            {
                string typeName = callRef.DeclaringType.FullName;
                
                if (callRef.Name == "Write")
                    this._writer.WriteLine($"\t\twriter.write(@Typeof(self.{name}), self.{name});");
                else if (callRef.Name == "Read")
                    this._writer.WriteLine($"\t\tself.{name} = reader.read(@TypeOf(self.{name}));");
                else if (callRef.Name is "Pack" or "Unpack")
                {
                    // Debug.Assert(typeName == type.BaseType!.FullName, $"{typeName} != {type.BaseType.Name}");
                    MethodInfo? subMethod = type.BaseType?.GetMethod(method.Name);
                    if (subMethod == null)
                    {
                        this._writer.WriteLine($"\t\t// FIXME: Could not find {method.Name} on {type.BaseType}");
                        continue;
                    }
                    WritePackFunction(type.BaseType!, subMethod);
                }
                else
                    this._writer.WriteLine($"\t\t// FIXME: Unknown {callRef.GetType().Name} {callRef}");
            }
        }

        if(_ilVerbose)
            this._writer.WriteLine($"\t\t// {type.Name} {method.Name.ToLower()}ed");
    }

    private string MapToZigType(Type type)
    {
        if (type == typeof(string))
            return "[]const u16";
        
        if (type == typeof(byte))
            return "u8";
        if (type == typeof(sbyte))
            return "i8";
        
        if (type == typeof(short))
            return "i16";
        if (type == typeof(ushort))
            return "u16";
        
        if (type == typeof(int))
            return "i32";
        if (type == typeof(uint))
            return "u32";
        
        if (type == typeof(long))
            return "i64";
        if (type == typeof(ulong))
            return "u64";
        
        if (type == typeof(Int128))
            return "i128";
        if (type == typeof(UInt128))
            return "u128";

        if (type == typeof(float))
            return "f32";
        if (type == typeof(double))
            return "f64";

        if (type == typeof(bool))
            return "bool";

        switch (type.Name)
        {
            case "RenderVector2":
                return "@Vector(2, f32)";
            case "RenderVector2i":
                return "@Vector(2, i32)";
            case "RenderVector3":
                return "@Vector(3, f32)";
            case "RenderVector3i":
                return "@Vector(3, i32)";
            case "RenderVector4" or "RenderQuaternion":
                return "@Vector(4, f32)";
            case "RenderVector4i":
                return "@Vector(4, i32)";
        }

        if (typeof(IEnumerable).IsAssignableFrom(type))
            return $"[]{MapToZigType(type.GenericTypeArguments.First())}";
        
        if(type.Name == "Nullable`1")
            return $"?{MapToZigType(type.GenericTypeArguments.First())}";

        if (type.IsGenericType)
            return $"{type.Name.Remove(type.Name.IndexOf('`'))}({string.Join(", ", type.GenericTypeArguments.Select(MapToZigType))})";

        if (!this._generatedTypes.Contains(type))
        {
            if (type.Assembly == this._assembly)
                this._typesToGenerate.Enqueue(type);
        }

        return type.Name;
    }

    public void Dispose()
    {
        this._writer.Flush();
        this._fileStream.Flush();
        
        this._writer.Dispose();
        this._fileStream.Dispose();
        GC.SuppressFinalize(this);
    }
}