using System.Diagnostics;
using System.Reflection;
using Mono.Cecil;
using NotEnoughLogs;
using RenderiteGenerator.Generator.TypeGenerators;
using RenderiteGenerator.Logging;
using RenderiteGenerator.Options;

namespace RenderiteGenerator.Generator;

public class Generator
{
    private readonly Logger _logger;
    private readonly GeneratorContext _context;
    private readonly Writer _writer;
    private readonly List<TypeGenerator> _generators = [];

    public Generator(Logger logger, GeneratorOptions options)
    {
        this._logger = logger;

        this._logger.LogInfo(LogCategory.Startup, "Loading FE assemblies...");
        this._context = new GeneratorContext
        {
            Assembly = Assembly.LoadFrom(options.AssemblyPath),
            AssemblyCecil = AssemblyDefinition.ReadAssembly(options.AssemblyPath),
            Options = options,
            Generator = this,
            Logger = this._logger,
        };

        this._context.Types = this._context.Assembly.GetTypes();
        this._logger.LogTrace(LogCategory.Startup, $"Loaded {this._context.Assembly.FullName}");
        
        string output = this._context.Options.OutputZigFile!;
        Debug.Assert(output != null);
        if (File.Exists(output))
        {
            this._logger.LogDebug(LogCategory.Output, "Deleting existing output zig file");
            File.Delete(output);
        }

        Debug.Assert(options.OutputZigFile != null);
        this._writer = new Writer(this._context, options.OutputZigFile);
        
        this._logger.LogInfo(LogCategory.Startup, "Finding FE version...");
        try
        {
            Assembly frooxEngine =
                Assembly.LoadFrom(Path.Combine(Path.GetDirectoryName(options.AssemblyPath)!, "FrooxEngine.dll"));

            this._context.EngineVersion = frooxEngine.FullName!;
            if (this._context.EngineVersion == null)
                throw new Exception("Engine version was null");
        }
        catch(Exception e)
        {
            this._logger.LogWarning(LogCategory.Startup, $"Couldn't get FrooxEngine assembly to determine version: {e}");
            this._logger.LogWarning(LogCategory.Startup, "Generation will continue but this won't be accepted in a PR.");
            this._context.EngineVersion = "Unknown";
        }
        
        this._logger.LogTrace(LogCategory.Startup, "Initializing type generators...");
        this._generators.Add(new PolymorphicGenerator(this._context));
        this._generators.Add(new PackableStructGenerator(this._context));
        this._generators.Add(new ExplicitStructGenerator(this._context));
        this._generators.Add(new EnumGenerator(this._context));
        this._generators.Add(new GeneralStructGenerator(this._context));
    }

    public void Run()
    {
        this._logger.LogInfo(LogCategory.Generator, $"Generating for engine version {this._context.EngineVersion}");
        
        Type? rootType = _context.Types.First(t => t.Name == "RendererCommand");
        if (rootType == null)
            throw new Exception("Could not find root type");
        Stopwatch stopwatch = Stopwatch.StartNew();
        
        this.RunInternal(this._writer, rootType);
        
        this._logger.LogInfo(LogCategory.Generator, $"Generated in {stopwatch.ElapsedMilliseconds}ms.");
        this._writer.Dispose();
    }

    private void RunInternal(Writer w, Type root)
    {
        w.Comment("This file is automatically generated by RenderiteGenerator. Please do not modify this file.");
        w.Comment($"Generated for {this._context.EngineVersion}\n");

        w.ImportZig("buffer");
        w.Define("SharedMemoryBufferDescriptor", "buffer");
        w.Line();
        w.ImportZig("serialization");
        w.Define("IpcDeserializer", "serialization");
        w.Define("IpcSerializer", "serialization");
        w.Line();
        w.Import("math");
        w.Line();
        
        this.GenerateType(root);
        // HACK: This doesn't get baked in because nothing accesses it
        this._context.TypeQueue.Enqueue(this._context.Types.First(t => t.Name == "TextureType"));
        while (_context.TypeQueue.TryDequeue(out Type? type))
        {
            Debug.Assert(type != null);
            this.GenerateType(type);
        }
    }

    private void GenerateType(Type type)
    {
        this._context.GeneratedTypes.Add(type);
        
        TypeGenerator? generator = GeneratorForType(type);
        if (generator == null)
        {
            this._logger.LogWarning(LogCategory.Generator, $"Missing generator for {type.FullName}");
            this._writer.Todo($"Missing generator for {type.FullName}");
            return;
        }

        this._logger.LogDebug(LogCategory.Generator, $"Generating type {type.FullName} with {generator.GetType().Name}");
        generator.Generate(type, this._writer);
        this._writer.Line();
    }

    private TypeGenerator? GeneratorForType(Type type)
    {
        return this._generators.FirstOrDefault(g => g.CanGenerateType(type));
    }
}