//! This file is automatically generated by RenderiteGenerator. Please do not modify this file.
// Generated for FrooxEngine, Version=2025.8.2.1133, Culture=neutral, PublicKeyToken=null

const buffer = @import("buffer.zig");
const SharedMemoryBufferDescriptor = buffer.SharedMemoryBufferDescriptor;

// Generated Enums
pub const ColorProfile = enum(i32) {
	Linear = 0,
	sRGB = 1,
	sRGBAlpha = 2,
};

pub const GaussianVectorFormat = enum(i32) {
	Float32 = 0,
	Norm16 = 1,
	Norm11 = 2,
	Norm6 = 3,
};

pub const GaussianRotationFormat = enum(i32) {
	PackedNorm10 = 0,
};

pub const GaussianColorFormat = enum(i32) {
	Float32x4 = 0,
	Float16x4 = 1,
	Norm8x4 = 2,
	BC7 = 3,
};

pub const GaussianSHFormat = enum(i32) {
	Float16 = 0,
	Norm11 = 1,
	Norm6 = 2,
	Cluster64k = 3,
	Cluster32k = 4,
	Cluster16k = 5,
	Cluster8k = 6,
	Cluster4k = 7,
};

pub const BlendshapeDataFlags = enum(i32) {
	NONE = 0,
	Positions = 1,
	Normals = 2,
	Tangets = 4,
};

pub const IndexBufferFormat = enum(i32) {
	UInt16 = 0,
	UInt32 = 1,
};

pub const SubmeshTopology = enum(i32) {
	Points = 0,
	Triangles = 1,
};

pub const VertexAttributeFormat = enum(i16) {
	Float32 = 0,
	Half16 = 1,
	UNorm8 = 2,
	UNorm16 = 3,
	SInt8 = 4,
	SInt16 = 5,
	SInt32 = 6,
	UInt8 = 7,
	UInt16 = 8,
	UInt32 = 9,
};

pub const VertexAttributeType = enum(i16) {
	Position = 0,
	Normal = 1,
	Tangent = 2,
	Color = 3,
	UV0 = 4,
	UV1 = 5,
	UV2 = 6,
	UV3 = 7,
	UV4 = 8,
	UV5 = 9,
	UV6 = 10,
	UV7 = 11,
	BoneWeights = 12,
	BoneIndicies = 13,
};

pub const TextureAssetType = enum(i32) {
	Texture2D = 0,
	Texture3D = 1,
	Cubemap = 2,
	RenderTexture = 3,
	VideoTexture = 4,
	Desktop = 5,
};

pub const TextureFilterMode = enum(i32) {
	Point = 0,
	Bilinear = 1,
	Trilinear = 2,
	Anisotropic = 3,
};

pub const TextureFormat = enum(i32) {
	Unknown = 0,
	Alpha8 = 1,
	R8 = 2,
	RGB24 = 16,
	ARGB32 = 17,
	RGBA32 = 18,
	BGRA32 = 19,
	RGB565 = 24,
	BGR565 = 25,
	RGBAHalf = 32,
	ARGBHalf = 33,
	RHalf = 34,
	RGHalf = 35,
	RGBAFloat = 48,
	ARGBFloat = 49,
	RFloat = 50,
	RGFloat = 51,
	BC1 = 64,
	BC2 = 65,
	BC3 = 66,
	BC4 = 67,
	BC5 = 68,
	BC6H = 69,
	BC7 = 70,
	ETC2_RGB = 96,
	ETC2_RGBA1 = 97,
	ETC2_RGBA8 = 98,
	ASTC_4x4 = 128,
	ASTC_5x5 = 129,
	ASTC_6x6 = 130,
	ASTC_8x8 = 131,
	ASTC_10x10 = 132,
	ASTC_12x12 = 133,
};

pub const TextureType = enum(i32) {
	Texture2D = 0,
	Cubemap = 1,
	Texture3D = 2,
};

pub const TextureWrapMode = enum(i32) {
	Repeat = 0,
	Clamp = 1,
	Mirror = 2,
	MirrorOnce = 3,
};

pub const Key = enum(i32) {
	None = 0,
	Backspace = 8,
	Tab = 9,
	Clear = 12,
	Return = 13,
	Pause = 19,
	Escape = 27,
	Space = 32,
	Exclaim = 33,
	DoubleQuote = 34,
	Hash = 35,
	Dollar = 36,
	Ampersand = 38,
	Quote = 39,
	LeftParenthesis = 40,
	RightParenthesis = 41,
	Asterisk = 42,
	Plus = 43,
	Comma = 44,
	Minus = 45,
	Period = 46,
	Slash = 47,
	Alpha0 = 48,
	Alpha1 = 49,
	Alpha2 = 50,
	Alpha3 = 51,
	Alpha4 = 52,
	Alpha5 = 53,
	Alpha6 = 54,
	Alpha7 = 55,
	Alpha8 = 56,
	Alpha9 = 57,
	Colon = 58,
	Semicolon = 59,
	Less = 60,
	Equals = 61,
	Greater = 62,
	Question = 63,
	At = 64,
	VerticalBar = 65,
	LeftBracket = 91,
	Backslash = 92,
	RightBracket = 93,
	Caret = 94,
	Underscore = 95,
	BackQuote = 96,
	A = 97,
	B = 98,
	C = 99,
	D = 100,
	E = 101,
	F = 102,
	G = 103,
	H = 104,
	I = 105,
	J = 106,
	K = 107,
	L = 108,
	M = 109,
	N = 110,
	O = 111,
	P = 112,
	Q = 113,
	R = 114,
	S = 115,
	T = 116,
	U = 117,
	V = 118,
	W = 119,
	X = 120,
	Y = 121,
	Z = 122,
	Percent = 123,
	Tilde = 124,
	LeftBrace = 125,
	RightBrace = 126,
	Delete = 127,
	Keypad0 = 256,
	Keypad1 = 257,
	Keypad2 = 258,
	Keypad3 = 259,
	Keypad4 = 260,
	Keypad5 = 261,
	Keypad6 = 262,
	Keypad7 = 263,
	Keypad8 = 264,
	Keypad9 = 265,
	KeypadPeriod = 266,
	KeypadDivide = 267,
	KeypadMultiply = 268,
	KeypadMinus = 269,
	KeypadPlus = 270,
	KeypadEnter = 271,
	KeypadEquals = 272,
	UpArrow = 273,
	DownArrow = 274,
	RightArrow = 275,
	LeftArrow = 276,
	Insert = 277,
	Home = 278,
	End = 279,
	PageUp = 280,
	PageDown = 281,
	F1 = 282,
	F2 = 283,
	F3 = 284,
	F4 = 285,
	F5 = 286,
	F6 = 287,
	F7 = 288,
	F8 = 289,
	F9 = 290,
	F10 = 291,
	F11 = 292,
	F12 = 293,
	F13 = 294,
	F14 = 295,
	F15 = 296,
	Numlock = 300,
	CapsLock = 301,
	ScrollLock = 302,
	RightShift = 303,
	LeftShift = 304,
	RightControl = 305,
	LeftControl = 306,
	RightAlt = 307,
	LeftAlt = 308,
	RightApple = 309,
	LeftApple = 310,
	LeftWindows = 311,
	RightWindows = 312,
	AltGr = 313,
	Help = 315,
	Print = 316,
	SysReq = 317,
	Break = 318,
	Menu = 319,
	Shift = 512,
	Control = 513,
	Alt = 514,
	Windows = 515,
};

pub const RectOrientation = enum(i32) {
	Default = 0,
	Clockwise90 = 1,
	UpsideDown180 = 2,
	CounterClockwise90 = 3,
};

pub const MaterialPropertyUpdateType = enum(u8) {
	SelectTarget = 0,
	SetShader = 1,
	SetRenderQueue = 2,
	SetInstancing = 3,
	SetRenderType = 4,
	SetFloat = 5,
	SetFloat4 = 6,
	SetFloat4x4 = 7,
	SetFloatArray = 8,
	SetFloat4Array = 9,
	SetTexture = 10,
	UpdateBatchEnd = 11,
};

pub const MaterialRenderType = enum(i32) {
	Opaque = 0,
	TransparentCutout = 1,
	Transparent = 2,
};

pub const TextureUpdateResultType = enum(i32) {
	FormatSet = 0,
	PropertiesSet = 1,
	DataUpload = 2,
};

pub const AntiAliasingMethod = enum(i32) {
	Off = 0,
	FXAA = 1,
	CTAA = 2,
	SMAA = 3,
	TAA = 4,
};

pub const ShadowCascadeMode = enum(i32) {
	None = 0,
	TwoCascades = 1,
	FourCascades = 2,
};

pub const ShadowResolutionMode = enum(i32) {
	Low = 0,
	Medium = 1,
	High = 2,
	Ultra = 3,
};

pub const SkinWeightMode = enum(i32) {
	OneBone = 0,
	TwoBones = 1,
	FourBones = 2,
	Unlimited = 3,
};

pub const HeadOutputDevice = enum(i32) {
	Autodetect = 0,
	Headless = 1,
	Screen = 2,
	Screen360 = 3,
	StaticCamera = 4,
	StaticCamera360 = 5,
	SteamVR = 6,
	WindowsMR = 7,
	Oculus = 8,
	OculusQuest = 9,
	UNKNOWN = 10,
};

pub const TouchControllerModel = enum(i8) {
	CV1 = 0,
	QuestAndRiftS = 1,
};

pub const HeadsetConnection = enum(i32) {
	Wired = 0,
	WirelessGeneral = 1,
	WirelessSteamLink = 2,
};

pub const CameraClearMode = enum(u8) {
	Skybox = 0,
	Color = 1,
	Depth = 2,
	Nothing = 3,
};

pub const CameraProjection = enum(u8) {
	Perspective = 0,
	Orthographic = 1,
	Panoramic = 2,
};

pub const ComputeResult = enum(i32) {
	Scheduled = 0,
	Computed = 1,
	Postpone = 2,
	Failed = 3,
};

pub const LayerType = enum(u8) {
	Hidden = 0,
	Overlay = 1,
};

pub const LightType = enum(u8) {
	Point = 0,
	Directional = 1,
	Spot = 2,
};

pub const ShadowType = enum(u8) {
	None = 0,
	Hard = 1,
	Soft = 2,
};

pub const ShadowCastMode = enum(u8) {
	Off = 0,
	On = 1,
	ShadowOnly = 2,
	DoubleSided = 3,
};

pub const MotionVectorMode = enum(u8) {
	Camera = 0,
	Object = 1,
	NoMotion = 2,
};

pub const MeshRendererType = enum(u8) {
	MeshRenderer = 0,
	SkinnedMeshRenderer = 1,
};

pub const ReflectionProbeClear = enum(u8) {
	Skybox = 0,
	Color = 1,
};

pub const ReflectionProbeType = enum(u8) {
	Baked = 0,
	OnChanges = 1,
	Realtime = 2,
};

pub const ReflectionProbeTimeSlicingMode = enum(u8) {
	AllFacesAtOnce = 0,
	IndividualFaces = 1,
	NoTimeSlicing = 2,
};

pub const BillboardAlignment = enum(u8) {
	View = 0,
	Facing = 1,
	Local = 2,
	Global = 3,
	Direction = 4,
};

pub const MeshAlignment = enum(u8) {
	View = 0,
	Facing = 1,
	Local = 2,
	Global = 3,
};

pub const TrailTextureMode = enum(u8) {
	Stretch = 0,
	Tile = 1,
	DistributePerSegment = 2,
	RepeatPerSegment = 3,
};

pub const RenderingContext = enum(u8) {
	UserView = 0,
	ExternalView = 1,
	Camera = 2,
	Mirror = 3,
	Portal = 4,
	RenderToAsset = 5,
};

pub const Chirality = enum(i8) {
	Left = 0,
	Right = 1,
};

pub const BodyNode = enum(i32) {
	NONE = 0,
	Root = 1,
	View = 2,
	LeftController = 3,
	RightController = 4,
	Hips = 5,
	Spine = 6,
	Chest = 7,
	UpperChest = 8,
	Neck = 9,
	Head = 10,
	Jaw = 11,
	LeftEye = 12,
	RightEye = 13,
	LeftShoulder = 14,
	LeftUpperArm = 15,
	LeftLowerArm = 16,
	LeftHand = 17,
	LeftPalm = 18,
	LeftThumb_Metacarpal = 19,
	LeftThumb_Proximal = 20,
	LeftThumb_Distal = 21,
	LeftThumb_Tip = 22,
	LeftIndexFinger_Metacarpal = 23,
	LeftIndexFinger_Proximal = 24,
	LeftIndexFinger_Intermediate = 25,
	LeftIndexFinger_Distal = 26,
	LeftIndexFinger_Tip = 27,
	LeftMiddleFinger_Metacarpal = 28,
	LeftMiddleFinger_Proximal = 29,
	LeftMiddleFinger_Intermediate = 30,
	LeftMiddleFinger_Distal = 31,
	LeftMiddleFinger_Tip = 32,
	LeftRingFinger_Metacarpal = 33,
	LeftRingFinger_Proximal = 34,
	LeftRingFinger_Intermediate = 35,
	LeftRingFinger_Distal = 36,
	LeftRingFinger_Tip = 37,
	LeftPinky_Metacarpal = 38,
	LeftPinky_Proximal = 39,
	LeftPinky_Intermediate = 40,
	LeftPinky_Distal = 41,
	LeftPinky_Tip = 42,
	RightShoulder = 43,
	RightUpperArm = 44,
	RightLowerArm = 45,
	RightHand = 46,
	RightPalm = 47,
	RightThumb_Metacarpal = 48,
	RightThumb_Proximal = 49,
	RightThumb_Distal = 50,
	RightThumb_Tip = 51,
	RightIndexFinger_Metacarpal = 52,
	RightIndexFinger_Proximal = 53,
	RightIndexFinger_Intermediate = 54,
	RightIndexFinger_Distal = 55,
	RightIndexFinger_Tip = 56,
	RightMiddleFinger_Metacarpal = 57,
	RightMiddleFinger_Proximal = 58,
	RightMiddleFinger_Intermediate = 59,
	RightMiddleFinger_Distal = 60,
	RightMiddleFinger_Tip = 61,
	RightRingFinger_Metacarpal = 62,
	RightRingFinger_Proximal = 63,
	RightRingFinger_Intermediate = 64,
	RightRingFinger_Distal = 65,
	RightRingFinger_Tip = 66,
	RightPinky_Metacarpal = 67,
	RightPinky_Proximal = 68,
	RightPinky_Intermediate = 69,
	RightPinky_Distal = 70,
	RIGHT_FINGER_END = 71,
	LeftUpperLeg = 72,
	LeftLowerLeg = 73,
	LeftFoot = 74,
	LeftToes = 75,
	RightUpperLeg = 76,
	RightLowerLeg = 77,
	RightFoot = 78,
	RightToes = 79,
	END = 80,
};

pub const FingerSegmentType = enum(i32) {
	Metacarpal = 0,
	Proximal = 1,
	Intermediate = 2,
	Distal = 3,
	Tip = 4,
};

pub const FingerType = enum(i32) {
	Thumb = 0,
	Index = 1,
	Middle = 2,
	Ring = 3,
	Pinky = 4,
};

pub const MeshUploadHint_Flag = enum(i32) {
	VertexLayout = 1,
	SubmeshLayout = 2,
	Geometry = 4,
	Positions = 8,
	Normals = 16,
	Tangents = 32,
	Colors = 64,
	UV0s = 128,
	UV1s = 256,
	UV2s = 512,
	UV3s = 1024,
	UV4s = 2048,
	UV5s = 4096,
	UV6s = 8192,
	UV7s = 16384,
	BindPoses = 32768,
	BoneWeights = 65536,
	Blendshapes = 131072,
	Dynamic = 262144,
	Readable = 524288,
	Debug = 1048576,
};

// Generated Structs
pub const GaussianSplatResult = struct {
	instanceChanged: bool,
	assetId: i32,
};

pub const GaussianSplatUploadEncoded = struct {
	positionsFormat: GaussianVectorFormat,
	rotationsFormat: GaussianRotationFormat,
	scalesFormat: GaussianVectorFormat,
	colorsFormat: GaussianColorFormat,
	shFormat: GaussianSHFormat,
	texture2DtextureAssetId: i32,
	shIndexesOffset: i32,
	chunkCount: i32,
	shBuffer: SharedMemoryBufferDescriptor(u8),
	chunksBuffer: SharedMemoryBufferDescriptor(u8),
	splatCount: i32,
	bounds: RenderBoundingBox,
	positionsBuffer: SharedMemoryBufferDescriptor(u8),
	rotationsBuffer: SharedMemoryBufferDescriptor(u8),
	scalesBuffer: SharedMemoryBufferDescriptor(u8),
	colorsBuffer: SharedMemoryBufferDescriptor(u8),
	assetId: i32,
};

pub const GaussianSplatUploadRaw = struct {
	alphasBuffer: SharedMemoryBufferDescriptor(u8),
	splatCount: i32,
	bounds: RenderBoundingBox,
	positionsBuffer: SharedMemoryBufferDescriptor(u8),
	rotationsBuffer: SharedMemoryBufferDescriptor(u8),
	scalesBuffer: SharedMemoryBufferDescriptor(u8),
	colorsBuffer: SharedMemoryBufferDescriptor(u8),
	assetId: i32,
};

pub const UnloadGaussianSplat = struct {
	assetId: i32,
};

pub const MaterialPropertyIdRequest = struct {
	requestId: i32,
	propertyNames: [][]const u16,
};

pub const MaterialPropertyIdResult = struct {
	requestId: i32,
	propertyIDs: []i32,
};

pub const MaterialsUpdateBatch = struct {
	updateBatchId: i32,
	materialRemovals: SharedMemoryBufferDescriptor(i32),
	materialPropertyBlockRemovals: SharedMemoryBufferDescriptor(i32),
	materialUpdates: []SharedMemoryBufferDescriptor(MaterialPropertyUpdate),
	materialUpdateCount: i32,
	intBuffers: []SharedMemoryBufferDescriptor(i32),
	floatBuffers: []SharedMemoryBufferDescriptor(f32),
	float4Buffers: []SharedMemoryBufferDescriptor(@Vector(4, f32)),
	matrixBuffers: []SharedMemoryBufferDescriptor(RenderMatrix4x4),
	instanceChangedBuffer: SharedMemoryBufferDescriptor(u32),
};

pub const MaterialsUpdateBatchResult = struct {
	updateBatchId: i32,
};

pub const MeshUnload = struct {
	assetId: i32,
};

pub const MeshUploadData = struct {
	highPriority: bool,
	buffer: SharedMemoryBufferDescriptor(u8),
	vertexCount: i32,
	boneWeightCount: i32,
	boneCount: i32,
	indexBufferFormat: IndexBufferFormat,
	vertexAttributes: []VertexAttributeDescriptor,
	submeshes: []SubmeshBufferDescriptor,
	blendshapeBuffers: []BlendshapeBufferDescriptor,
	uploadHint: MeshUploadHint,
	bounds: RenderBoundingBox,
	assetId: i32,
};

pub const MeshUploadResult = struct {
	instanceChanged: bool,
	assetId: i32,
};

pub const PointRenderBufferConsumed = struct {
	assetId: i32,
};

pub const PointRenderBufferUnload = struct {
	assetId: i32,
};

pub const PointRenderBufferUpload = struct {
	count: i32,
	positionsOffset: i32,
	rotationsOffset: i32,
	sizesOffset: i32,
	colorsOffset: i32,
	frameIndexesOffset: i32,
	frameGridSize: @Vector(2, i32),
	buffer: SharedMemoryBufferDescriptor(u8),
	assetId: i32,
};

pub const TrailRenderBufferConsumed = struct {
	assetId: i32,
};

pub const TrailRenderBufferUnload = struct {
	assetId: i32,
};

pub const TrailRenderBufferUpload = struct {
	trailsCount: i32,
	trailPointCount: i32,
	trailsOffset: i32,
	positionsOffset: i32,
	colorsOffset: i32,
	sizesOffset: i32,
	buffer: SharedMemoryBufferDescriptor(u8),
	assetId: i32,
};

pub const ShaderUnload = struct {
	assetId: i32,
};

pub const ShaderUpload = struct {
	file: []const u16,
	assetId: i32,
};

pub const ShaderUploadResult = struct {
	instanceChanged: bool,
	assetId: i32,
};

pub const SetCubemapData = struct {
	data: SharedMemoryBufferDescriptor(u8),
	startMipLevel: i32,
	mipMapSizes: []@Vector(2, i32),
	mipStarts: [][]i32,
	flipY: bool,
	highPriority: bool,
	assetId: i32,
};

pub const SetCubemapFormat = struct {
	size: i32,
	mipmapCount: i32,
	format: TextureFormat,
	profile: ColorProfile,
	assetId: i32,
};

pub const SetCubemapProperties = struct {
	filterMode: TextureFilterMode,
	anisoLevel: i32,
	mipmapBias: f32,
	applyImmediatelly: bool,
	highPriority: bool,
	assetId: i32,
};

pub const SetCubemapResult = struct {
	type: TextureUpdateResultType,
	instanceChanged: bool,
	assetId: i32,
};

pub const UnloadCubemap = struct {
	assetId: i32,
};

pub const DesktopTexturePropertiesUpdate = struct {
	size: @Vector(2, i32),
	assetId: i32,
};

pub const SetDesktopTextureProperties = struct {
	displayIndex: i32,
	assetId: i32,
};

pub const UnloadDesktopTexture = struct {
	assetId: i32,
};

pub const RenderTextureResult = struct {
	instanceChanged: bool,
	assetId: i32,
};

pub const SetRenderTextureFormat = struct {
	size: @Vector(2, i32),
	depth: i32,
	filterMode: TextureFilterMode,
	anisoLevel: i32,
	wrapU: TextureWrapMode,
	wrapV: TextureWrapMode,
	assetId: i32,
};

pub const UnloadRenderTexture = struct {
	assetId: i32,
};

pub const SetTexture2DData = struct {
	data: SharedMemoryBufferDescriptor(u8),
	startMipLevel: i32,
	mipMapSizes: []@Vector(2, i32),
	mipStarts: []i32,
	flipY: bool,
	hint: TextureUploadHint,
	highPriority: bool,
	assetId: i32,
};

pub const SetTexture2DFormat = struct {
	width: i32,
	height: i32,
	mipmapCount: i32,
	format: TextureFormat,
	profile: ColorProfile,
	assetId: i32,
};

pub const SetTexture2DProperties = struct {
	filterMode: TextureFilterMode,
	anisoLevel: i32,
	wrapU: TextureWrapMode,
	wrapV: TextureWrapMode,
	mipmapBias: f32,
	applyImmediatelly: bool,
	highPriority: bool,
	assetId: i32,
};

pub const SetTexture2DResult = struct {
	type: TextureUpdateResultType,
	instanceChanged: bool,
	assetId: i32,
};

pub const UnloadTexture2D = struct {
	assetId: i32,
};

pub const SetTexture3DData = struct {
	data: SharedMemoryBufferDescriptor(u8),
	hint: Texture3DUploadHint,
	highPriority: bool,
	assetId: i32,
};

pub const SetTexture3DFormat = struct {
	width: i32,
	height: i32,
	depth: i32,
	mipmapCount: i32,
	format: TextureFormat,
	profile: ColorProfile,
	assetId: i32,
};

pub const SetTexture3DProperties = struct {
	filterMode: TextureFilterMode,
	anisoLevel: i32,
	wrapU: TextureWrapMode,
	wrapV: TextureWrapMode,
	wrapW: TextureWrapMode,
	applyImmediatelly: bool,
	highPriority: bool,
	assetId: i32,
};

pub const SetTexture3DResult = struct {
	type: TextureUpdateResultType,
	instanceChanged: bool,
	assetId: i32,
};

pub const UnloadTexture3D = struct {
	assetId: i32,
};

pub const UnloadVideoTexture = struct {
	assetId: i32,
};

pub const VideoAudioTrack = struct {
	index: i32,
	channelCount: i32,
	sampleRate: i32,
	name: []const u16,
	languageCode: []const u16,
};

pub const VideoTextureChanged = struct {
	assetId: i32,
};

pub const VideoTextureLoad = struct {
	source: []const u16,
	overrideEngine: []const u16,
	mimeType: []const u16,
	isStream: bool,
	audioSystemSampleRate: i32,
	assetId: i32,
};

pub const VideoTextureProperties = struct {
	filterMode: TextureFilterMode,
	anisoLevel: i32,
	wrapU: TextureWrapMode,
	wrapV: TextureWrapMode,
	assetId: i32,
};

pub const VideoTextureReady = struct {
	length: f64,
	size: @Vector(2, i32),
	hasAlpha: bool,
	playbackEngine: []const u16,
	instanceChanged: bool,
	audioTracks: []VideoAudioTrack,
	assetId: i32,
};

pub const VideoTextureStartAudioTrack = struct {
	audioTrackIndex: i32,
	queueCapacity: i32,
	queueName: []const u16,
	assetId: i32,
};

pub const VideoTextureUpdate = struct {
	position: f64,
	play: bool,
	loop: bool,
	assetId: i32,
};

pub const DesktopConfig = struct {
	maximumBackgroundFramerate: ?i32,
	maximumForegroundFramerate: ?i32,
	vSync: bool,
};

pub const GaussianSplatConfig = struct {
	sortingMegaOperationsPerCamera: f32,
};

pub const PostProcessingConfig = struct {
	motionBlurIntensity: f32,
	bloomIntensity: f32,
	ambientOcclusionIntensity: f32,
	screenSpaceReflections: bool,
	antialiasing: AntiAliasingMethod,
};

pub const QualityConfig = struct {
	perPixelLight: i32,
	shadowCascades: ShadowCascadeMode,
	shadowResolution: ShadowResolutionMode,
	shadowDistance: f32,
	skinWeightMode: SkinWeightMode,
};

pub const ResolutionConfig = struct {
	resolution: @Vector(2, i32),
	fullscreen: bool,
};

pub const CameraRenderParameters = struct {
	resolution: @Vector(2, i32),
	textureFormat: TextureFormat,
	projection: CameraProjection,
	fov: f32,
	orthographicSize: f32,
	clearMode: CameraClearMode,
	clearColor: @Vector(4, f32),
	nearClip: f32,
	farClip: f32,
	renderPrivateUI: bool,
	postProcessing: bool,
	screenSpaceReflections: bool,
};

pub const CameraRenderTask = struct {
	renderSpaceId: i32,
	position: @Vector(3, f32),
	rotation: @Vector(4, f32),
	parameters: CameraRenderParameters,
	resultData: SharedMemoryBufferDescriptor(u8),
	onlyRenderList: []i32,
	excludeRenderList: []i32,
};

pub const FrameStartData = struct {
	lastFrameIndex: i32,
	performance: PerformanceState,
	inputs: InputState,
	renderedReflectionProbes: []RenderableHandle,
};

pub const FrameSubmitData = struct {
	frameIndex: i32,
	debugLog: bool,
	vrActive: bool,
	nearClip: f32,
	farClip: f32,
	desktopFOV: f32,
	outputState: OutputState,
	renderSpaces: []RenderSpaceUpdate,
	renderTasks: []CameraRenderTask,
};

pub const KeepAlive = struct {
};

pub const PerformanceState = struct {
	fps: f32,
	immediateFPS: f32,
	renderTime: f32,
	externalUpdateTime: f32,
	frameBeginToSubmitTime: f32,
	frameProcessedToNextBeginTime: f32,
	integrationProcessingTime: f32,
	extraParticleProcessingTime: f32,
	processedAssetIntegratorTasks: i32,
	integrationHighPriorityTasks: i32,
	integrationTasks: i32,
	integrationRenderTasks: i32,
	integrationParticleTasks: i32,
	processingHandleWaits: i32,
	frameUpdateHandleTime: f32,
	renderedCameras: i32,
	renderedCameraPortals: i32,
	updatedTextures: i32,
	textureSliceUploads: i32,
};

pub const ReflectionProbeRenderResult = struct {
	renderTaskId: i32,
	success: bool,
};

pub const ReflectionProbeRenderTask = struct {
	renderableIndex: i32,
	renderTaskId: i32,
	size: i32,
	hdr: bool,
	mipOrigins: [][]i32,
	resultData: SharedMemoryBufferDescriptor(u8),
	excludeTransformIds: []i32,
};

pub const RenderSpaceUpdate = struct {
	id: i32,
	isActive: bool,
	isOverlay: bool,
	isPrivate: bool,
	rootTransform: RenderTransform,
	viewPositionIsExternal: bool,
	overrideViewPosition: bool,
	skyboxMaterialAssetId: i32,
	ambientLight: RenderSH2,
	overridenViewTransform: RenderTransform,
	transformsUpdate: TransformsUpdate,
	meshRenderersUpdate: MeshRenderablesUpdate,
	skinnedMeshRenderersUpdate: SkinnedMeshRenderablesUpdate,
	lightsUpdate: LightRenderablesUpdate,
	camerasUpdate: CameraRenderablesUpdate,
	cameraPortalsUpdate: CameraPortalsRenderablesUpdate,
	reflectionProbesUpdate: ReflectionProbeRenderablesUpdate,
	reflectionProbeSH2Taks: ReflectionProbeSH2Tasks,
	layersUpdate: LayerUpdate,
	billboardBuffersUpdate: BillboardRenderBufferUpdate,
	meshRenderBuffersUpdate: MeshRenderBufferUpdate,
	trailRenderersUpdate: TrailsRendererUpdate,
	lightsBufferRenderersUpdate: LightsBufferRendererUpdate,
	renderTransformOverridesUpdate: RenderTransformOverridesUpdate,
	renderMaterialOverridesUpdate: RenderMaterialOverridesUpdate,
	blitToDisplaysUpdate: BlitToDisplayRenderablesUpdate,
	lodGroupUpdate: LODGroupRenderablesUpdate,
	gaussianSplatRenderersUpdate: GaussianSplatRenderablesUpdate,
	reflectionProbeRenderTasks: []ReflectionProbeRenderTask,
};

pub const DisplayState = struct {
	displayIndex: i32,
	resolution: @Vector(2, i32),
	offset: @Vector(2, i32),
	refreshRate: f64,
	orientation: RectOrientation,
	dpi: @Vector(2, f32),
	isPrimary: bool,
};

pub const DragAndDropEvent = struct {
	paths: [][]const u16,
	dropPoint: @Vector(2, i32),
};

pub const GamepadState = struct {
	displayName: []const u16,
	leftThumbstick: @Vector(2, f32),
	rightThumbstick: @Vector(2, f32),
	dPad: @Vector(2, f32),
	leftTrigger: f32,
	rightTrigger: f32,
	leftThumbstickClick: bool,
	rightThumbstickClick: bool,
	dPadUp: bool,
	dPadRight: bool,
	dPadDown: bool,
	dPadLeft: bool,
	leftBumper: bool,
	rightBumper: bool,
	start: bool,
	menu: bool,
	a: bool,
	b: bool,
	x: bool,
	y: bool,
	paddle0: bool,
	paddle1: bool,
	paddle2: bool,
	paddle3: bool,
};

pub const HandState = struct {
	uniqueId: []const u16,
	priority: i32,
	chirality: Chirality,
	isDeviceActive: bool,
	isTracking: bool,
	tracksMetacarpals: bool,
	confidence: f32,
	wristPosition: @Vector(3, f32),
	wristRotation: @Vector(4, f32),
	segmentPositions: []@Vector(3, f32),
	segmentRotations: []@Vector(4, f32),
};

pub const InputState = struct {
	mouse: MouseState,
	keyboard: KeyboardState,
	window: WindowState,
	vr: VR_InputsState,
	gamepads: []GamepadState,
	touches: []TouchState,
	displays: []DisplayState,
};

pub const KeyboardState = struct {
	typeDelta: []const u16,
	heldKeys: []Key,
};

pub const MouseState = struct {
	isActive: bool,
	leftButtonState: bool,
	rightButtonState: bool,
	middleButtonState: bool,
	button4State: bool,
	button5State: bool,
	desktopPosition: @Vector(2, f32),
	windowPosition: @Vector(2, f32),
	directDelta: @Vector(2, f32),
	scrollWheelDelta: @Vector(2, f32),
};

pub const TouchState = struct {
	touchId: i32,
	position: @Vector(2, f32),
	isPressing: bool,
	pressure: f32,
};

pub const CosmosControllerState = struct {
	joystickTouch: bool,
	joystickClick: bool,
	joystickRaw: @Vector(2, f32),
	triggerTouch: bool,
	triggerClick: bool,
	trigger: f32,
	gripClick: bool,
	vive: bool,
	buttonAX: bool,
	buttonBY: bool,
	bumper: bool,
	deviceID: []const u16,
	deviceModel: []const u16,
	side: Chirality,
	bodyNode: BodyNode,
	isDeviceActive: bool,
	isTracking: bool,
	position: @Vector(3, f32),
	rotation: @Vector(4, f32),
	hasBoundHand: bool,
	handPosition: @Vector(3, f32),
	handRotation: @Vector(4, f32),
	batteryLevel: f32,
	batteryCharging: bool,
};

pub const GenericControllerState = struct {
	strength: f32,
	axis: @Vector(2, f32),
	touchingStrength: bool,
	touchingAxis: bool,
	primary: bool,
	menu: bool,
	grab: bool,
	secondary: bool,
	deviceID: []const u16,
	deviceModel: []const u16,
	side: Chirality,
	bodyNode: BodyNode,
	isDeviceActive: bool,
	isTracking: bool,
	position: @Vector(3, f32),
	rotation: @Vector(4, f32),
	hasBoundHand: bool,
	handPosition: @Vector(3, f32),
	handRotation: @Vector(4, f32),
	batteryLevel: f32,
	batteryCharging: bool,
};

pub const HP_ReverbControllerState = struct {
	appMenu: bool,
	buttonYB: bool,
	buttonXA: bool,
	gripTouch: bool,
	gripClick: bool,
	grip: f32,
	joystickClick: bool,
	joystickRaw: @Vector(2, f32),
	triggerHair: bool,
	triggerClick: bool,
	trigger: f32,
	deviceID: []const u16,
	deviceModel: []const u16,
	side: Chirality,
	bodyNode: BodyNode,
	isDeviceActive: bool,
	isTracking: bool,
	position: @Vector(3, f32),
	rotation: @Vector(4, f32),
	hasBoundHand: bool,
	handPosition: @Vector(3, f32),
	handRotation: @Vector(4, f32),
	batteryLevel: f32,
	batteryCharging: bool,
};

pub const IndexControllerState = struct {
	grip: f32,
	gripTouch: bool,
	gripClick: bool,
	buttonA: bool,
	buttonB: bool,
	buttonAtouch: bool,
	buttonBtouch: bool,
	trigger: f32,
	triggerTouch: bool,
	triggerClick: bool,
	joystickRaw: @Vector(2, f32),
	joystickTouch: bool,
	joystickClick: bool,
	touchpad: @Vector(2, f32),
	touchpadTouch: bool,
	touchpadPress: bool,
	touchpadForce: f32,
	deviceID: []const u16,
	deviceModel: []const u16,
	side: Chirality,
	bodyNode: BodyNode,
	isDeviceActive: bool,
	isTracking: bool,
	position: @Vector(3, f32),
	rotation: @Vector(4, f32),
	hasBoundHand: bool,
	handPosition: @Vector(3, f32),
	handRotation: @Vector(4, f32),
	batteryLevel: f32,
	batteryCharging: bool,
};

pub const PicoNeo2ControllerState = struct {
	app: bool,
	pico: bool,
	buttonYB: bool,
	buttonXA: bool,
	gripClick: bool,
	joystickTouch: bool,
	joystickClick: bool,
	joystick: @Vector(2, f32),
	triggerClick: bool,
	trigger: f32,
	deviceID: []const u16,
	deviceModel: []const u16,
	side: Chirality,
	bodyNode: BodyNode,
	isDeviceActive: bool,
	isTracking: bool,
	position: @Vector(3, f32),
	rotation: @Vector(4, f32),
	hasBoundHand: bool,
	handPosition: @Vector(3, f32),
	handRotation: @Vector(4, f32),
	batteryLevel: f32,
	batteryCharging: bool,
};

pub const TouchControllerState = struct {
	model: TouchControllerModel,
	start: bool,
	buttonYB: bool,
	buttonXA: bool,
	buttonYB_touch: bool,
	buttonXA_touch: bool,
	thumbrestTouch: bool,
	grip: f32,
	gripClick: bool,
	joystickRaw: @Vector(2, f32),
	joystickTouch: bool,
	joystickClick: bool,
	trigger: f32,
	triggerTouch: bool,
	triggerClick: bool,
	deviceID: []const u16,
	deviceModel: []const u16,
	side: Chirality,
	bodyNode: BodyNode,
	isDeviceActive: bool,
	isTracking: bool,
	position: @Vector(3, f32),
	rotation: @Vector(4, f32),
	hasBoundHand: bool,
	handPosition: @Vector(3, f32),
	handRotation: @Vector(4, f32),
	batteryLevel: f32,
	batteryCharging: bool,
};

pub const ViveControllerState = struct {
	grip: bool,
	app: bool,
	triggerHair: bool,
	triggerClick: bool,
	trigger: f32,
	touchpadTouch: bool,
	touchpadClick: bool,
	touchpad: @Vector(2, f32),
	deviceID: []const u16,
	deviceModel: []const u16,
	side: Chirality,
	bodyNode: BodyNode,
	isDeviceActive: bool,
	isTracking: bool,
	position: @Vector(3, f32),
	rotation: @Vector(4, f32),
	hasBoundHand: bool,
	handPosition: @Vector(3, f32),
	handRotation: @Vector(4, f32),
	batteryLevel: f32,
	batteryCharging: bool,
};

pub const WindowsMR_ControllerState = struct {
	grip: bool,
	app: bool,
	triggerHair: bool,
	triggerClick: bool,
	trigger: f32,
	touchpadTouch: bool,
	touchpadClick: bool,
	touchpad: @Vector(2, f32),
	joystickClick: bool,
	joystickRaw: @Vector(2, f32),
	deviceID: []const u16,
	deviceModel: []const u16,
	side: Chirality,
	bodyNode: BodyNode,
	isDeviceActive: bool,
	isTracking: bool,
	position: @Vector(3, f32),
	rotation: @Vector(4, f32),
	hasBoundHand: bool,
	handPosition: @Vector(3, f32),
	handRotation: @Vector(4, f32),
	batteryLevel: f32,
	batteryCharging: bool,
};

pub const HeadsetState = struct {
	isTracking: bool,
	position: @Vector(3, f32),
	rotation: @Vector(4, f32),
	batteryLevel: f32,
	batteryCharging: bool,
	connectionType: HeadsetConnection,
	headsetManufacturer: []const u16,
	headsetModel: []const u16,
};

pub const TrackerState = struct {
	uniqueId: []const u16,
	isTracking: bool,
	position: @Vector(3, f32),
	rotation: @Vector(4, f32),
	batteryLevel: f32,
	batteryCharging: bool,
};

pub const TrackingReferenceState = struct {
	uniqueId: []const u16,
	isTracking: bool,
	position: @Vector(3, f32),
	rotation: @Vector(4, f32),
};

pub const VR_InputsState = struct {
	userPresentInHeadset: bool,
	dashboardOpen: bool,
	headsetState: HeadsetState,
	controllers: []VR_ControllerState,
	trackers: []TrackerState,
	trackingReferences: []TrackingReferenceState,
	hands: []HandState,
};

pub const WindowState = struct {
	isWindowFocused: bool,
	isFullscreen: bool,
	windowResolution: @Vector(2, i32),
	resolutionSettingsApplied: bool,
	dragAndDropEvent: DragAndDropEvent,
};

pub const OutputState = struct {
	lockCursor: bool,
	lockCursorPosition: ?@Vector(2, i32),
	keyboardInputActive: bool,
	vr: VR_OutputState,
};

pub const VR_ControllerOutputState = struct {
	side: Chirality,
	vibrateTime: f64,
	hapticState: HapticPointState,
};

pub const VR_OutputState = struct {
	leftController: VR_ControllerOutputState,
	rightController: VR_ControllerOutputState,
};

pub const BillboardRenderBufferUpdate = struct {
	states: SharedMemoryBufferDescriptor(BillboardRenderBufferState),
	removals: SharedMemoryBufferDescriptor(i32),
	additions: SharedMemoryBufferDescriptor(i32),
};

pub const BlitToDisplayRenderablesUpdate = struct {
	states: SharedMemoryBufferDescriptor(BlitToDisplayState),
	removals: SharedMemoryBufferDescriptor(i32),
	additions: SharedMemoryBufferDescriptor(i32),
};

pub const CameraPortalsRenderablesUpdate = struct {
	states: SharedMemoryBufferDescriptor(CameraPortalState),
	removals: SharedMemoryBufferDescriptor(i32),
	additions: SharedMemoryBufferDescriptor(i32),
};

pub const CameraRenderablesUpdate = struct {
	transformIds: SharedMemoryBufferDescriptor(i32),
	states: SharedMemoryBufferDescriptor(CameraState),
	removals: SharedMemoryBufferDescriptor(i32),
	additions: SharedMemoryBufferDescriptor(i32),
};

pub const RenderMaterialOverridesUpdate = struct {
	materialOverrideStates: SharedMemoryBufferDescriptor(MaterialOverrideState),
	states: SharedMemoryBufferDescriptor(RenderMaterialOverrideState),
	removals: SharedMemoryBufferDescriptor(i32),
	additions: SharedMemoryBufferDescriptor(i32),
};

pub const RenderTransformOverridesUpdate = struct {
	skinnedMeshRenderersIndexes: SharedMemoryBufferDescriptor(i32),
	states: SharedMemoryBufferDescriptor(RenderTransformOverrideState),
	removals: SharedMemoryBufferDescriptor(i32),
	additions: SharedMemoryBufferDescriptor(i32),
};

pub const GaussianSplatRenderablesUpdate = struct {
	states: SharedMemoryBufferDescriptor(GaussianSplatRendererState),
	removals: SharedMemoryBufferDescriptor(i32),
	additions: SharedMemoryBufferDescriptor(i32),
};

pub const LayerUpdate = struct {
	layerAssignments: SharedMemoryBufferDescriptor(LayerType),
	removals: SharedMemoryBufferDescriptor(i32),
	additions: SharedMemoryBufferDescriptor(i32),
};

pub const LightsBufferRendererConsumed = struct {
	globalUniqueId: i32,
};

pub const LightsBufferRendererSubmission = struct {
	lightsBufferUniqueId: i32,
	lightsCount: i32,
	lights: SharedMemoryBufferDescriptor(LightData),
};

pub const LightsBufferRendererUpdate = struct {
	states: SharedMemoryBufferDescriptor(LightsBufferRendererState),
	removals: SharedMemoryBufferDescriptor(i32),
	additions: SharedMemoryBufferDescriptor(i32),
};

pub const LightRenderablesUpdate = struct {
	states: SharedMemoryBufferDescriptor(LightState),
	removals: SharedMemoryBufferDescriptor(i32),
	additions: SharedMemoryBufferDescriptor(i32),
};

pub const LODGroupRenderablesUpdate = struct {
	lodStates: SharedMemoryBufferDescriptor(LODState),
	packedMeshRendererIds: SharedMemoryBufferDescriptor(i32),
	states: SharedMemoryBufferDescriptor(LODGroupState),
	removals: SharedMemoryBufferDescriptor(i32),
	additions: SharedMemoryBufferDescriptor(i32),
};

pub const MeshRenderBufferUpdate = struct {
	states: SharedMemoryBufferDescriptor(MeshRenderBufferState),
	removals: SharedMemoryBufferDescriptor(i32),
	additions: SharedMemoryBufferDescriptor(i32),
};

pub const MeshRenderablesUpdate = struct {
	meshStates: SharedMemoryBufferDescriptor(MeshRendererState),
	meshMaterialsAndPropertyBlocks: SharedMemoryBufferDescriptor(i32),
	removals: SharedMemoryBufferDescriptor(i32),
	additions: SharedMemoryBufferDescriptor(i32),
};

pub const ReflectionProbeRenderablesUpdate = struct {
	changedProbesToRender: SharedMemoryBufferDescriptor(i32),
	states: SharedMemoryBufferDescriptor(ReflectionProbeState),
	removals: SharedMemoryBufferDescriptor(i32),
	additions: SharedMemoryBufferDescriptor(i32),
};

pub const SkinnedMeshRenderablesUpdate = struct {
	boundsUpdates: SharedMemoryBufferDescriptor(SkinnedMeshBoundsUpdate),
	realtimeBoundsUpdates: SharedMemoryBufferDescriptor(SkinnedMeshRealtimeBoundsUpdate),
	boneAssignments: SharedMemoryBufferDescriptor(BoneAssignment),
	boneTransformIndexes: SharedMemoryBufferDescriptor(i32),
	blendshapeUpdateBatches: SharedMemoryBufferDescriptor(BlendshapeUpdateBatch),
	blendshapeUpdates: SharedMemoryBufferDescriptor(BlendshapeUpdate),
	meshStates: SharedMemoryBufferDescriptor(MeshRendererState),
	meshMaterialsAndPropertyBlocks: SharedMemoryBufferDescriptor(i32),
	removals: SharedMemoryBufferDescriptor(i32),
	additions: SharedMemoryBufferDescriptor(i32),
};

pub const ReflectionProbeSH2Tasks = struct {
	tasks: SharedMemoryBufferDescriptor(ReflectionProbeSH2Task),
	removals: SharedMemoryBufferDescriptor(i32),
	additions: SharedMemoryBufferDescriptor(i32),
};

pub const TrailsRendererUpdate = struct {
	states: SharedMemoryBufferDescriptor(TrailsRendererState),
	removals: SharedMemoryBufferDescriptor(i32),
	additions: SharedMemoryBufferDescriptor(i32),
};

pub const TransformsUpdate = struct {
	targetTransformCount: i32,
	removals: SharedMemoryBufferDescriptor(i32),
	parentUpdates: SharedMemoryBufferDescriptor(TransformParentUpdate),
	poseUpdates: SharedMemoryBufferDescriptor(TransformPoseUpdate),
};

pub const RendererInitData = struct {
	sharedMemoryPrefix: []const u16,
	mainProcessId: i32,
	debugFramePacing: bool,
	outputDevice: HeadOutputDevice,
	windowTitle: []const u16,
};

pub const RendererInitFinalizeData = struct {
};

pub const RendererInitProgressUpdate = struct {
	phaseIndex: i32,
	phase: []const u16,
	subPhase: []const u16,
	forceShow: bool,
};

pub const RendererInitResult = struct {
	actualOutputDevice: HeadOutputDevice,
	stereoRenderingMode: []const u16,
	maxTextureSize: i32,
	isGPUTexturePOTByteAligned: bool,
	supportedTextureFormats: []TextureFormat,
};

pub const RendererShutdown = struct {
};

pub const RendererShutdownRequest = struct {
};

pub const RenderBoundingBox = struct {
	center: @Vector(3, f32),
	extents: @Vector(3, f32),
};

pub const MaterialPropertyUpdate = struct {
	propertyID: i32,
	updateType: MaterialPropertyUpdateType,
};

pub const RenderMatrix4x4 = struct {
	m00: f32,
	m10: f32,
	m20: f32,
	m30: f32,
	m01: f32,
	m11: f32,
	m21: f32,
	m31: f32,
	m02: f32,
	m12: f32,
	m22: f32,
	m32: f32,
	m03: f32,
	m13: f32,
	m23: f32,
	m33: f32,
};

pub const VertexAttributeDescriptor = struct {
	attribute: VertexAttributeType,
	format: VertexAttributeFormat,
	dimensions: i32,
};

pub const SubmeshBufferDescriptor = struct {
	topology: SubmeshTopology,
	indexStart: i32,
	indexCount: i32,
	bounds: RenderBoundingBox,
};

pub const BlendshapeBufferDescriptor = struct {
	blendshapeIndex: i32,
	frameIndex: i32,
	frameWeight: f32,
	dataFlags: BlendshapeDataFlags,
};

pub const MeshUploadHint = struct {
};

pub const TextureUploadHint = struct {
	regionData: RenderIntRect,
	readable: bool,
	hasRegion: bool,
};

pub const Texture3DUploadHint = struct {
	readable: bool,
};

pub const RenderableHandle = struct {
	renderSpaceId: i32,
	renderableIndex: i32,
};

pub const RenderTransform = struct {
	position: @Vector(3, f32),
	scale: @Vector(3, f32),
	rotation: @Vector(4, f32),
};

pub const RenderSH2 = struct {
	sh0: @Vector(3, f32),
	sh1: @Vector(3, f32),
	sh2: @Vector(3, f32),
	sh3: @Vector(3, f32),
	sh4: @Vector(3, f32),
	sh5: @Vector(3, f32),
	sh6: @Vector(3, f32),
	sh7: @Vector(3, f32),
	sh8: @Vector(3, f32),
};

pub const VR_ControllerState = struct {
	deviceID: []const u16,
	deviceModel: []const u16,
	side: Chirality,
	bodyNode: BodyNode,
	isDeviceActive: bool,
	isTracking: bool,
	position: @Vector(3, f32),
	rotation: @Vector(4, f32),
	hasBoundHand: bool,
	handPosition: @Vector(3, f32),
	handRotation: @Vector(4, f32),
	batteryLevel: f32,
	batteryCharging: bool,
};

pub const HapticPointState = struct {
	force: f32,
	temperature: f32,
	pain: f32,
	vibration: f32,
};

pub const BillboardRenderBufferState = struct {
	renderableIndex: i32,
	pointRenderBufferAssetId: i32,
	materialAssetId: i32,
	minBillboardScreenSize: f32,
	maxBillboardScreenSize: f32,
	alignment: BillboardAlignment,
	motionVectorMode: MotionVectorMode,
};

pub const BlitToDisplayState = struct {
	renderableIndex: i32,
	textureId: i32,
	backgroundColor: @Vector(4, f32),
	displayIndex: i16,
};

pub const CameraPortalState = struct {
	renderableIndex: i32,
	meshRendererIndex: i32,
	planeNormal: @Vector(3, f32),
	planeOffset: f32,
	renderTextureId: i32,
	portalTransform: RenderMatrix4x4,
	portalPlanePosition: @Vector(3, f32),
	portalPlaneNormal: @Vector(3, f32),
};

pub const CameraState = struct {
	renderableIndex: i32,
	fieldOfView: f32,
	orthographicSize: f32,
	nearClip: f32,
	farClip: f32,
	backgroundColor: @Vector(4, f32),
	viewport: RenderRect,
	depth: f32,
	renderTextureAssetId: i32,
	selectiveRenderCount: i32,
	excludeRenderCount: i32,
	clearMode: CameraClearMode,
	projection: CameraProjection,
};

pub const MaterialOverrideState = struct {
	materialSlotIndex: i32,
	materialAssetId: i32,
};

pub const RenderMaterialOverrideState = struct {
	renderableIndex: i32,
	packedMeshRendererIndex: i32,
	materrialOverrideCount: i16,
	context: RenderingContext,
};

pub const RenderTransformOverrideState = struct {
	renderableIndex: i32,
	positionOverride: @Vector(3, f32),
	rotationOverride: @Vector(4, f32),
	scaleOverride: @Vector(3, f32),
	skinnedMeshRendererCount: i32,
	context: RenderingContext,
	overrideFlags: u8,
};

pub const GaussianSplatRendererState = struct {
	renderableIndex: i32,
	gaussianSplatAssetId: i32,
	sizeScale: f32,
	opacityScale: f32,
	maxSHOrder: i32,
	sphericalHamornicsOnly: bool,
};

pub const LightData = struct {
	point: @Vector(3, f32),
	orientation: @Vector(4, f32),
	color: @Vector(3, f32),
	intensity: f32,
	range: f32,
	angle: f32,
};

pub const LightsBufferRendererState = struct {
	renderableIndex: i32,
	globalUniqueId: i32,
	shadowStrength: f32,
	shadowNearPlane: f32,
	shadowMapResolution: i32,
	shadowBias: f32,
	shadowNormalBias: f32,
	cookieTextureAssetId: i32,
	lightType: LightType,
	shadowType: ShadowType,
};

pub const LightState = struct {
	renderableIndex: i32,
	intensity: f32,
	range: f32,
	spotAngle: f32,
	color: @Vector(4, f32),
	shadowStrength: f32,
	shadowNearPlane: f32,
	shadowMapResolutionOverride: i32,
	shadowBias: f32,
	shadowNormalBias: f32,
	cookieTextureAssetId: i32,
	type: LightType,
	shadowType: ShadowType,
};

pub const LODState = struct {
	screenRelativeTransitionHeight: f32,
	fadeTransitionWidth: f32,
	rendererCount: i32,
};

pub const LODGroupState = struct {
	renderableIndex: i32,
	lodCount: i32,
	crossFade: bool,
	animateCrossFading: bool,
};

pub const MeshRenderBufferState = struct {
	renderableIndex: i32,
	pointRenderBufferAssetId: i32,
	materialAssetId: i32,
	meshAssetId: i32,
	alignment: MeshAlignment,
};

pub const MeshRendererState = struct {
	renderableIndex: i32,
	meshAssetId: i32,
	materialCount: i32,
	materialPropertyBlockCount: i32,
	sortingOrder: i32,
	shadowCastMode: ShadowCastMode,
	motionVectorMode: MotionVectorMode,
};

pub const ReflectionProbeState = struct {
	renderableIndex: i32,
	importance: i32,
	intensity: f32,
	blendDistance: f32,
	boxSize: @Vector(3, f32),
	cubemapAssetId: i32,
	resolution: i32,
	shadowDistance: f32,
	backgroundColor: @Vector(4, f32),
	nearClip: f32,
	farClip: f32,
	type: ReflectionProbeType,
	clearFlags: ReflectionProbeClear,
	timeSlicingMode: ReflectionProbeTimeSlicingMode,
};

pub const SkinnedMeshBoundsUpdate = struct {
	renderableIndex: i32,
	localBounds: RenderBoundingBox,
};

pub const SkinnedMeshRealtimeBoundsUpdate = struct {
	renderableIndex: i32,
	computedGlobalBounds: RenderBoundingBox,
};

pub const BoneAssignment = struct {
	renderableIndex: i32,
	rootBoneTransformId: i32,
	boneCount: i32,
};

pub const BlendshapeUpdateBatch = struct {
	renderableIndex: i32,
	blendshapeUpdateCount: i32,
};

pub const BlendshapeUpdate = struct {
	blendshapeIndex: i32,
	weight: f32,
};

pub const ReflectionProbeSH2Task = struct {
	renderableIndex: i32,
	reflectionProbeRenderableIndex: i32,
	result: ComputeResult,
	resultData: RenderSH2,
};

pub const TrailsRendererState = struct {
	renderableIndex: i32,
	trailsRenderBufferAssetId: i32,
	materialAssetId: i32,
	textureMode: TrailTextureMode,
	motionVectorMode: MotionVectorMode,
	generateLightingData: bool,
};

pub const TransformParentUpdate = struct {
	transformId: i32,
	newParentId: i32,
};

pub const TransformPoseUpdate = struct {
	transformId: i32,
	pose: RenderTransform,
};

pub const RenderIntRect = struct {
	x: i32,
	y: i32,
	width: i32,
	height: i32,
};

pub const RenderRect = struct {
	x: f32,
	y: f32,
	width: f32,
	height: f32,
};

