// This file is automatically generated by RenderiteGenerator. Please do not modify this file.
// Generated for FrooxEngine, Version=2025.8.11.521, Culture=neutral, PublicKeyToken=null

const buffer = @import("buffer.zig");
const SharedMemoryBufferDescriptor = buffer.SharedMemoryBufferDescriptor;

const serialization = @import("serialization.zig");
const IpcDeserializer = serialization.IpcDeserializer;
const IpcSerializer = serialization.IpcSerializer;

const math = @import("math");

pub const RendererCommandTypes = enum(i32) {
    RendererInitData,
    RendererInitResult,
    RendererInitProgressUpdate,
    RendererInitFinalizeData,
    RendererShutdownRequest,
    RendererShutdown,
    KeepAlive,
    RendererParentWindow,
    FrameStartData,
    FrameSubmitData,
    PostProcessingConfig,
    QualityConfig,
    ResolutionConfig,
    DesktopConfig,
    GaussianSplatConfig,
    MeshUploadData,
    MeshUnload,
    MeshUploadResult,
    ShaderUpload,
    ShaderUnload,
    ShaderUploadResult,
    MaterialPropertyIdRequest,
    MaterialPropertyIdResult,
    MaterialsUpdateBatch,
    MaterialsUpdateBatchResult,
    SetTexture2DFormat,
    SetTexture2DProperties,
    SetTexture2DData,
    SetTexture2DResult,
    UnloadTexture2D,
    SetTexture3DFormat,
    SetTexture3DProperties,
    SetTexture3DData,
    SetTexture3DResult,
    UnloadTexture3D,
    SetCubemapFormat,
    SetCubemapProperties,
    SetCubemapData,
    SetCubemapResult,
    UnloadCubemap,
    SetRenderTextureFormat,
    RenderTextureResult,
    UnloadRenderTexture,
    SetDesktopTextureProperties,
    DesktopTexturePropertiesUpdate,
    UnloadDesktopTexture,
    PointRenderBufferUpload,
    PointRenderBufferConsumed,
    PointRenderBufferUnload,
    TrailRenderBufferUpload,
    TrailRenderBufferConsumed,
    TrailRenderBufferUnload,
    GaussianSplatUploadRaw,
    GaussianSplatUploadEncoded,
    GaussianSplatResult,
    UnloadGaussianSplat,
    LightsBufferRendererSubmission,
    LightsBufferRendererConsumed,
    ReflectionProbeRenderResult,
    VideoTextureLoad,
    VideoTextureUpdate,
    VideoTextureReady,
    VideoTextureChanged,
    VideoTextureProperties,
    VideoTextureStartAudioTrack,
    UnloadVideoTexture,
};
pub const RendererCommand = union(RendererCommandTypes) {
    RendererInitData: RendererInitData,
    RendererInitResult: RendererInitResult,
    RendererInitProgressUpdate: RendererInitProgressUpdate,
    RendererInitFinalizeData: RendererInitFinalizeData,
    RendererShutdownRequest: RendererShutdownRequest,
    RendererShutdown: RendererShutdown,
    KeepAlive: KeepAlive,
    RendererParentWindow: RendererParentWindow,
    FrameStartData: FrameStartData,
    FrameSubmitData: FrameSubmitData,
    PostProcessingConfig: PostProcessingConfig,
    QualityConfig: QualityConfig,
    ResolutionConfig: ResolutionConfig,
    DesktopConfig: DesktopConfig,
    GaussianSplatConfig: GaussianSplatConfig,
    MeshUploadData: MeshUploadData,
    MeshUnload: MeshUnload,
    MeshUploadResult: MeshUploadResult,
    ShaderUpload: ShaderUpload,
    ShaderUnload: ShaderUnload,
    ShaderUploadResult: ShaderUploadResult,
    MaterialPropertyIdRequest: MaterialPropertyIdRequest,
    MaterialPropertyIdResult: MaterialPropertyIdResult,
    MaterialsUpdateBatch: MaterialsUpdateBatch,
    MaterialsUpdateBatchResult: MaterialsUpdateBatchResult,
    SetTexture2DFormat: SetTexture2DFormat,
    SetTexture2DProperties: SetTexture2DProperties,
    SetTexture2DData: SetTexture2DData,
    SetTexture2DResult: SetTexture2DResult,
    UnloadTexture2D: UnloadTexture2D,
    SetTexture3DFormat: SetTexture3DFormat,
    SetTexture3DProperties: SetTexture3DProperties,
    SetTexture3DData: SetTexture3DData,
    SetTexture3DResult: SetTexture3DResult,
    UnloadTexture3D: UnloadTexture3D,
    SetCubemapFormat: SetCubemapFormat,
    SetCubemapProperties: SetCubemapProperties,
    SetCubemapData: SetCubemapData,
    SetCubemapResult: SetCubemapResult,
    UnloadCubemap: UnloadCubemap,
    SetRenderTextureFormat: SetRenderTextureFormat,
    RenderTextureResult: RenderTextureResult,
    UnloadRenderTexture: UnloadRenderTexture,
    SetDesktopTextureProperties: SetDesktopTextureProperties,
    DesktopTexturePropertiesUpdate: DesktopTexturePropertiesUpdate,
    UnloadDesktopTexture: UnloadDesktopTexture,
    PointRenderBufferUpload: PointRenderBufferUpload,
    PointRenderBufferConsumed: PointRenderBufferConsumed,
    PointRenderBufferUnload: PointRenderBufferUnload,
    TrailRenderBufferUpload: TrailRenderBufferUpload,
    TrailRenderBufferConsumed: TrailRenderBufferConsumed,
    TrailRenderBufferUnload: TrailRenderBufferUnload,
    GaussianSplatUploadRaw: GaussianSplatUploadRaw,
    GaussianSplatUploadEncoded: GaussianSplatUploadEncoded,
    GaussianSplatResult: GaussianSplatResult,
    UnloadGaussianSplat: UnloadGaussianSplat,
    LightsBufferRendererSubmission: LightsBufferRendererSubmission,
    LightsBufferRendererConsumed: LightsBufferRendererConsumed,
    ReflectionProbeRenderResult: ReflectionProbeRenderResult,
    VideoTextureLoad: VideoTextureLoad,
    VideoTextureUpdate: VideoTextureUpdate,
    VideoTextureReady: VideoTextureReady,
    VideoTextureChanged: VideoTextureChanged,
    VideoTextureProperties: VideoTextureProperties,
    VideoTextureStartAudioTrack: VideoTextureStartAudioTrack,
    UnloadVideoTexture: UnloadVideoTexture,
};
// FIXME: Missing generator for Renderite.Shared.RendererInitData
// FIXME: Missing generator for Renderite.Shared.RendererInitResult
// FIXME: Missing generator for Renderite.Shared.RendererInitProgressUpdate
// FIXME: Missing generator for Renderite.Shared.RendererInitFinalizeData
// FIXME: Missing generator for Renderite.Shared.RendererShutdownRequest
// FIXME: Missing generator for Renderite.Shared.RendererShutdown
// FIXME: Missing generator for Renderite.Shared.KeepAlive
// FIXME: Missing generator for Renderite.Shared.RendererParentWindow
// FIXME: Missing generator for Renderite.Shared.FrameStartData
// FIXME: Missing generator for Renderite.Shared.FrameSubmitData
// FIXME: Missing generator for Renderite.Shared.PostProcessingConfig
// FIXME: Missing generator for Renderite.Shared.QualityConfig
// FIXME: Missing generator for Renderite.Shared.ResolutionConfig
// FIXME: Missing generator for Renderite.Shared.DesktopConfig
// FIXME: Missing generator for Renderite.Shared.GaussianSplatConfig
// FIXME: Missing generator for Renderite.Shared.MeshUploadData
// FIXME: Missing generator for Renderite.Shared.MeshUnload
// FIXME: Missing generator for Renderite.Shared.MeshUploadResult
// FIXME: Missing generator for Renderite.Shared.ShaderUpload
// FIXME: Missing generator for Renderite.Shared.ShaderUnload
// FIXME: Missing generator for Renderite.Shared.ShaderUploadResult
// FIXME: Missing generator for Renderite.Shared.MaterialPropertyIdRequest
// FIXME: Missing generator for Renderite.Shared.MaterialPropertyIdResult
// FIXME: Missing generator for Renderite.Shared.MaterialsUpdateBatch
// FIXME: Missing generator for Renderite.Shared.MaterialsUpdateBatchResult
// FIXME: Missing generator for Renderite.Shared.SetTexture2DFormat
// FIXME: Missing generator for Renderite.Shared.SetTexture2DProperties
// FIXME: Missing generator for Renderite.Shared.SetTexture2DData
// FIXME: Missing generator for Renderite.Shared.SetTexture2DResult
// FIXME: Missing generator for Renderite.Shared.UnloadTexture2D
// FIXME: Missing generator for Renderite.Shared.SetTexture3DFormat
// FIXME: Missing generator for Renderite.Shared.SetTexture3DProperties
// FIXME: Missing generator for Renderite.Shared.SetTexture3DData
// FIXME: Missing generator for Renderite.Shared.SetTexture3DResult
// FIXME: Missing generator for Renderite.Shared.UnloadTexture3D
// FIXME: Missing generator for Renderite.Shared.SetCubemapFormat
// FIXME: Missing generator for Renderite.Shared.SetCubemapProperties
// FIXME: Missing generator for Renderite.Shared.SetCubemapData
// FIXME: Missing generator for Renderite.Shared.SetCubemapResult
// FIXME: Missing generator for Renderite.Shared.UnloadCubemap
// FIXME: Missing generator for Renderite.Shared.SetRenderTextureFormat
// FIXME: Missing generator for Renderite.Shared.RenderTextureResult
// FIXME: Missing generator for Renderite.Shared.UnloadRenderTexture
// FIXME: Missing generator for Renderite.Shared.SetDesktopTextureProperties
// FIXME: Missing generator for Renderite.Shared.DesktopTexturePropertiesUpdate
// FIXME: Missing generator for Renderite.Shared.UnloadDesktopTexture
// FIXME: Missing generator for Renderite.Shared.PointRenderBufferUpload
// FIXME: Missing generator for Renderite.Shared.PointRenderBufferConsumed
// FIXME: Missing generator for Renderite.Shared.PointRenderBufferUnload
// FIXME: Missing generator for Renderite.Shared.TrailRenderBufferUpload
// FIXME: Missing generator for Renderite.Shared.TrailRenderBufferConsumed
// FIXME: Missing generator for Renderite.Shared.TrailRenderBufferUnload
// FIXME: Missing generator for Renderite.Shared.GaussianSplatUploadRaw
// FIXME: Missing generator for Renderite.Shared.GaussianSplatUploadEncoded
// FIXME: Missing generator for Renderite.Shared.GaussianSplatResult
// FIXME: Missing generator for Renderite.Shared.UnloadGaussianSplat
// FIXME: Missing generator for Renderite.Shared.LightsBufferRendererSubmission
// FIXME: Missing generator for Renderite.Shared.LightsBufferRendererConsumed
// FIXME: Missing generator for Renderite.Shared.ReflectionProbeRenderResult
// FIXME: Missing generator for Renderite.Shared.VideoTextureLoad
// FIXME: Missing generator for Renderite.Shared.VideoTextureUpdate
// FIXME: Missing generator for Renderite.Shared.VideoTextureReady
// FIXME: Missing generator for Renderite.Shared.VideoTextureChanged
// FIXME: Missing generator for Renderite.Shared.VideoTextureProperties
// FIXME: Missing generator for Renderite.Shared.VideoTextureStartAudioTrack
// FIXME: Missing generator for Renderite.Shared.UnloadVideoTexture
