//! This file is automatically generated by RenderiteGenerator. Please do not modify this file.

pub const ColorProfile = enum(i32) {
	Linear = 0,
	sRGB = 1,
	sRGBAlpha = 2,
}

pub const BlendshapeDataFlags = enum(i32) {
	NONE = 0,
	Positions = 1,
	Normals = 2,
	Tangets = 4,
}

pub const IndexBufferFormat = enum(i32) {
	UInt16 = 0,
	UInt32 = 1,
}

pub const SubmeshTopology = enum(i32) {
	Points = 0,
	Triangles = 1,
}

pub const VertexAttributeFormat = enum(i16) {
	Float32 = 0,
	Half16 = 1,
	UNorm8 = 2,
	UNorm16 = 3,
	SInt8 = 4,
	SInt16 = 5,
	SInt32 = 6,
	UInt8 = 7,
	UInt16 = 8,
	UInt32 = 9,
}

pub const VertexAttributeType = enum(i16) {
	Position = 0,
	Normal = 1,
	Tangent = 2,
	Color = 3,
	UV0 = 4,
	UV1 = 5,
	UV2 = 6,
	UV3 = 7,
	UV4 = 8,
	UV5 = 9,
	UV6 = 10,
	UV7 = 11,
	BoneWeights = 12,
	BoneIndicies = 13,
}

pub const TextureAssetType = enum(i32) {
	Texture2D = 0,
	Texture3D = 1,
	Cubemap = 2,
	RenderTexture = 3,
	VideoTexture = 4,
	Desktop = 5,
}

pub const TextureFilterMode = enum(i32) {
	Point = 0,
	Bilinear = 1,
	Trilinear = 2,
	Anisotropic = 3,
}

pub const TextureFormat = enum(i32) {
	Unknown = 0,
	Alpha8 = 1,
	R8 = 2,
	RGB24 = 16,
	ARGB32 = 17,
	RGBA32 = 18,
	BGRA32 = 19,
	RGB565 = 24,
	BGR565 = 25,
	RGBAHalf = 32,
	ARGBHalf = 33,
	RHalf = 34,
	RGHalf = 35,
	RGBAFloat = 48,
	ARGBFloat = 49,
	RFloat = 50,
	RGFloat = 51,
	BC1 = 64,
	BC2 = 65,
	BC3 = 66,
	BC4 = 67,
	BC5 = 68,
	BC6H = 69,
	BC7 = 70,
	ETC2_RGB = 96,
	ETC2_RGBA1 = 97,
	ETC2_RGBA8 = 98,
	ASTC_4x4 = 128,
	ASTC_5x5 = 129,
	ASTC_6x6 = 130,
	ASTC_8x8 = 131,
	ASTC_10x10 = 132,
	ASTC_12x12 = 133,
}

pub const TextureType = enum(i32) {
	Texture2D = 0,
	Cubemap = 1,
	Texture3D = 2,
}

pub const TextureWrapMode = enum(i32) {
	Repeat = 0,
	Clamp = 1,
	Mirror = 2,
	MirrorOnce = 3,
}

pub const Key = enum(i32) {
	None = 0,
	Backspace = 8,
	Tab = 9,
	Clear = 12,
	Return = 13,
	Pause = 19,
	Escape = 27,
	Space = 32,
	Exclaim = 33,
	DoubleQuote = 34,
	Hash = 35,
	Dollar = 36,
	Ampersand = 38,
	Quote = 39,
	LeftParenthesis = 40,
	RightParenthesis = 41,
	Asterisk = 42,
	Plus = 43,
	Comma = 44,
	Minus = 45,
	Period = 46,
	Slash = 47,
	Alpha0 = 48,
	Alpha1 = 49,
	Alpha2 = 50,
	Alpha3 = 51,
	Alpha4 = 52,
	Alpha5 = 53,
	Alpha6 = 54,
	Alpha7 = 55,
	Alpha8 = 56,
	Alpha9 = 57,
	Colon = 58,
	Semicolon = 59,
	Less = 60,
	Equals = 61,
	Greater = 62,
	Question = 63,
	At = 64,
	VerticalBar = 65,
	LeftBracket = 91,
	Backslash = 92,
	RightBracket = 93,
	Caret = 94,
	Underscore = 95,
	BackQuote = 96,
	A = 97,
	B = 98,
	C = 99,
	D = 100,
	E = 101,
	F = 102,
	G = 103,
	H = 104,
	I = 105,
	J = 106,
	K = 107,
	L = 108,
	M = 109,
	N = 110,
	O = 111,
	P = 112,
	Q = 113,
	R = 114,
	S = 115,
	T = 116,
	U = 117,
	V = 118,
	W = 119,
	X = 120,
	Y = 121,
	Z = 122,
	Percent = 123,
	Tilde = 124,
	LeftBrace = 125,
	RightBrace = 126,
	Delete = 127,
	Keypad0 = 256,
	Keypad1 = 257,
	Keypad2 = 258,
	Keypad3 = 259,
	Keypad4 = 260,
	Keypad5 = 261,
	Keypad6 = 262,
	Keypad7 = 263,
	Keypad8 = 264,
	Keypad9 = 265,
	KeypadPeriod = 266,
	KeypadDivide = 267,
	KeypadMultiply = 268,
	KeypadMinus = 269,
	KeypadPlus = 270,
	KeypadEnter = 271,
	KeypadEquals = 272,
	UpArrow = 273,
	DownArrow = 274,
	RightArrow = 275,
	LeftArrow = 276,
	Insert = 277,
	Home = 278,
	End = 279,
	PageUp = 280,
	PageDown = 281,
	F1 = 282,
	F2 = 283,
	F3 = 284,
	F4 = 285,
	F5 = 286,
	F6 = 287,
	F7 = 288,
	F8 = 289,
	F9 = 290,
	F10 = 291,
	F11 = 292,
	F12 = 293,
	F13 = 294,
	F14 = 295,
	F15 = 296,
	Numlock = 300,
	CapsLock = 301,
	ScrollLock = 302,
	RightShift = 303,
	LeftShift = 304,
	RightControl = 305,
	LeftControl = 306,
	RightAlt = 307,
	LeftAlt = 308,
	RightApple = 309,
	RightApple = 309,
	LeftApple = 310,
	LeftApple = 310,
	LeftWindows = 311,
	RightWindows = 312,
	AltGr = 313,
	Help = 315,
	Print = 316,
	SysReq = 317,
	Break = 318,
	Menu = 319,
	Shift = 512,
	Control = 513,
	Alt = 514,
	Windows = 515,
}

pub const RectOrientation = enum(i32) {
	Default = 0,
	Clockwise90 = 1,
	UpsideDown180 = 2,
	CounterClockwise90 = 3,
}

pub const MaterialPropertyUpdateType = enum(u8) {
	SelectTarget = 0,
	SetShader = 1,
	SetRenderQueue = 2,
	SetInstancing = 3,
	SetRenderType = 4,
	SetFloat = 5,
	SetFloat4 = 6,
	SetFloat4x4 = 7,
	SetFloatArray = 8,
	SetFloat4Array = 9,
	SetTexture = 10,
	UpdateBatchEnd = 11,
}

pub const MaterialRenderType = enum(i32) {
	Opaque = 0,
	TransparentCutout = 1,
	Transparent = 2,
}

pub const TextureUpdateResultType = enum(i32) {
	FormatSet = 0,
	PropertiesSet = 1,
	DataUpload = 2,
}

pub const AntiAliasingMethod = enum(i32) {
	Off = 0,
	FXAA = 1,
	CTAA = 2,
	SMAA = 3,
	TAA = 4,
}

pub const ShadowCascadeMode = enum(i32) {
	None = 0,
	TwoCascades = 1,
	FourCascades = 2,
}

pub const ShadowResolutionMode = enum(i32) {
	Low = 0,
	Medium = 1,
	High = 2,
	Ultra = 3,
}

pub const SkinWeightMode = enum(i32) {
	OneBone = 0,
	TwoBones = 1,
	FourBones = 2,
	Unlimited = 3,
}

pub const HeadOutputDevice = enum(i32) {
	Autodetect = 0,
	Headless = 1,
	Screen = 2,
	Screen360 = 3,
	StaticCamera = 4,
	StaticCamera360 = 5,
	SteamVR = 6,
	WindowsMR = 7,
	Oculus = 8,
	OculusQuest = 9,
	UNKNOWN = 10,
}

pub const TouchControllerModel = enum(i8) {
	CV1 = 0,
	QuestAndRiftS = 1,
}

pub const HeadsetConnection = enum(i32) {
	Wired = 0,
	WirelessGeneral = 1,
	WirelessSteamLink = 2,
}

pub const CameraClearMode = enum(u8) {
	Skybox = 0,
	Color = 1,
	Depth = 2,
	Nothing = 3,
}

pub const CameraProjection = enum(u8) {
	Perspective = 0,
	Orthographic = 1,
	Panoramic = 2,
}

pub const ComputeResult = enum(i32) {
	Scheduled = 0,
	Computed = 1,
	Postpone = 2,
	Failed = 3,
}

pub const LayerType = enum(u8) {
	Hidden = 0,
	Overlay = 1,
}

pub const LightType = enum(u8) {
	Point = 0,
	Directional = 1,
	Spot = 2,
}

pub const ShadowType = enum(u8) {
	None = 0,
	Hard = 1,
	Soft = 2,
}

pub const ShadowCastMode = enum(u8) {
	Off = 0,
	On = 1,
	ShadowOnly = 2,
	DoubleSided = 3,
}

pub const MotionVectorMode = enum(u8) {
	Camera = 0,
	Object = 1,
	NoMotion = 2,
}

pub const MeshRendererType = enum(u8) {
	MeshRenderer = 0,
	SkinnedMeshRenderer = 1,
}

pub const ReflectionProbeClear = enum(u8) {
	Skybox = 0,
	Color = 1,
}

pub const ReflectionProbeType = enum(u8) {
	Baked = 0,
	OnChanges = 1,
	Realtime = 2,
}

pub const ReflectionProbeTimeSlicingMode = enum(u8) {
	AllFacesAtOnce = 0,
	IndividualFaces = 1,
	NoTimeSlicing = 2,
}

pub const BillboardAlignment = enum(u8) {
	View = 0,
	Facing = 1,
	Local = 2,
	Global = 3,
	Direction = 4,
}

pub const MeshAlignment = enum(u8) {
	View = 0,
	Facing = 1,
	Local = 2,
	Global = 3,
}

pub const TrailTextureMode = enum(u8) {
	Stretch = 0,
	Tile = 1,
	DistributePerSegment = 2,
	RepeatPerSegment = 3,
}

pub const RenderingContext = enum(u8) {
	UserView = 0,
	ExternalView = 1,
	Camera = 2,
	Mirror = 3,
	Portal = 4,
	RenderToAsset = 5,
}

pub const Chirality = enum(i8) {
	Left = 0,
	Right = 1,
}

pub const BodyNode = enum(i32) {
	NONE = 0,
	Root = 1,
	View = 2,
	LeftController = 3,
	RightController = 4,
	Hips = 5,
	Spine = 6,
	Chest = 7,
	UpperChest = 8,
	Neck = 9,
	Head = 10,
	Jaw = 11,
	LeftEye = 12,
	RightEye = 13,
	LeftShoulder = 14,
	LeftUpperArm = 15,
	LeftLowerArm = 16,
	LeftHand = 17,
	LeftPalm = 18,
	LeftThumb_Metacarpal = 19,
	LeftThumb_Metacarpal = 19,
	LeftThumb_Proximal = 20,
	LeftThumb_Distal = 21,
	LeftThumb_Tip = 22,
	LeftIndexFinger_Metacarpal = 23,
	LeftIndexFinger_Proximal = 24,
	LeftIndexFinger_Intermediate = 25,
	LeftIndexFinger_Distal = 26,
	LeftIndexFinger_Tip = 27,
	LeftMiddleFinger_Metacarpal = 28,
	LeftMiddleFinger_Proximal = 29,
	LeftMiddleFinger_Intermediate = 30,
	LeftMiddleFinger_Distal = 31,
	LeftMiddleFinger_Tip = 32,
	LeftRingFinger_Metacarpal = 33,
	LeftRingFinger_Proximal = 34,
	LeftRingFinger_Intermediate = 35,
	LeftRingFinger_Distal = 36,
	LeftRingFinger_Tip = 37,
	LeftPinky_Metacarpal = 38,
	LeftPinky_Proximal = 39,
	LeftPinky_Intermediate = 40,
	LeftPinky_Distal = 41,
	LeftPinky_Tip = 42,
	LeftPinky_Tip = 42,
	RightShoulder = 43,
	RightUpperArm = 44,
	RightLowerArm = 45,
	RightHand = 46,
	RightPalm = 47,
	RightThumb_Metacarpal = 48,
	RightThumb_Metacarpal = 48,
	RightThumb_Proximal = 49,
	RightThumb_Distal = 50,
	RightThumb_Tip = 51,
	RightIndexFinger_Metacarpal = 52,
	RightIndexFinger_Proximal = 53,
	RightIndexFinger_Intermediate = 54,
	RightIndexFinger_Distal = 55,
	RightIndexFinger_Tip = 56,
	RightMiddleFinger_Metacarpal = 57,
	RightMiddleFinger_Proximal = 58,
	RightMiddleFinger_Intermediate = 59,
	RightMiddleFinger_Distal = 60,
	RightMiddleFinger_Tip = 61,
	RightRingFinger_Metacarpal = 62,
	RightRingFinger_Proximal = 63,
	RightRingFinger_Intermediate = 64,
	RightRingFinger_Distal = 65,
	RightRingFinger_Tip = 66,
	RightPinky_Metacarpal = 67,
	RightPinky_Proximal = 68,
	RightPinky_Intermediate = 69,
	RightPinky_Distal = 70,
	RIGHT_FINGER_END = 71,
	RIGHT_FINGER_END = 71,
	LeftUpperLeg = 72,
	LeftLowerLeg = 73,
	LeftFoot = 74,
	LeftToes = 75,
	RightUpperLeg = 76,
	RightLowerLeg = 77,
	RightFoot = 78,
	RightToes = 79,
	END = 80,
}

pub const FingerSegmentType = enum(i32) {
	Metacarpal = 0,
	Proximal = 1,
	Intermediate = 2,
	Distal = 3,
	Tip = 4,
}

pub const FingerType = enum(i32) {
	Thumb = 0,
	Index = 1,
	Middle = 2,
	Ring = 3,
	Pinky = 4,
}

pub const MeshUploadHint_Flag = enum(i32) {
	VertexLayout = 1,
	SubmeshLayout = 2,
	Geometry = 4,
	Positions = 8,
	Normals = 16,
	Tangents = 32,
	Colors = 64,
	UV0s = 128,
	UV1s = 256,
	UV2s = 512,
	UV3s = 1024,
	UV4s = 2048,
	UV5s = 4096,
	UV6s = 8192,
	UV7s = 16384,
	BindPoses = 32768,
	BoneWeights = 65536,
	Blendshapes = 131072,
	Dynamic = 262144,
	Readable = 524288,
	Debug = 1048576,
}

