on: [push, pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-2025]
        target: ['native', 'x86_64-windows', 'x86_64-linux-gnu', 'aarch64-linux-gnu']
        optimize: ['Debug', 'ReleaseSafe', 'ReleaseFast']
    name: Compile Build
    steps:
      - name: Install Dependencies
        if: matrix.os == 'ubuntu-24.04'
        run: |
          mkdir dxc && cd dxc
          wget https://github.com/microsoft/DirectXShaderCompiler/releases/download/v1.8.2505.1/linux_dxc_2025_07_14.x86_64.tar.gz
          tar -xzf linux_dxc_2025_07_14.x86_64.tar.gz
          cd ..
          echo "$PWD/dxc/bin" >> "$GITHUB_PATH"
          echo "$PWD/dxc/lib" >> "$GITHUB_PATH"
      - name: Install Dependencies
        if: matrix.os == 'windows-2025'
        shell: bash
        run: |
          # install DXC 
          mkdir dxc && cd dxc
          curl -L -o dxc_2025_07_14.zip https://github.com/microsoft/DirectXShaderCompiler/releases/download/v1.8.2505.1/dxc_2025_07_14.zip
          7z x dxc_2025_07_14.zip
          cd ..
          echo "$PWD/dxc/bin" >> "$GITHUB_PATH"
          echo "$PWD/dxc/lib" >> "$GITHUB_PATH"
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.0-dev.1283+1fcaf90dd
          cache-key: ${{ matrix.target }}_${{ matrix.optimize }}_${{ matrix.os }}
          cache-size-limit: 512 # 512mb
      - name: Build & Install with stub XR backend
        if: matrix.target == 'native'
        run: zig build -Dtarget=${{ matrix.target }} -Doptimize=${{ matrix.optimize }} -Dxr_backend=none --summary all install
      - name: Build & Install with OpenXR backend
        run: zig build -Dtarget=${{ matrix.target }} -Doptimize=${{ matrix.optimize }} -Dxr_backend=openxr --summary all install
      - name: Run Tests
        if: matrix.target == 'native'
        run: zig build -Dtarget=${{ matrix.target }} -Doptimize=${{ matrix.optimize }} --summary all test
      - name: Upload Build
        if: matrix.os == 'ubuntu-latest' && matrix.target != 'native' && (matrix.optimize == 'ReleaseSafe' || matrix.optimize == 'Debug')
        uses: actions/upload-artifact@v4
        with:
          path: zig-out/bin
          name: ${{ matrix.target }} - ${{ matrix.optimize }}
